
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.services;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.BatchService;
import com.sdk.test.vdm.namespaces.sfodataedmx.AddModifierToJobReqFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.ApproveOfferFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.ApproveOrDeclineJobReqFormFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.ApproveWfRequestFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica;
import com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaByKeyFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaCreateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaDeleteFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaUpdateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.CheckUserPermissionFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.CheckUserPermissionsFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.CommentWfRequestFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.ConvertAssignmentIdExternalFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.CreatePerformanceReviewFormFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.DeclineOfferFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.FwdCandidateToColleagueFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GenerateNextPersonIDFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetBizXActionFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetDefaultDevGoalPlanTemplateIdFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetDefaultGoalPlanTemplateIdFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetDocumentCategoriesFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetDynamicGroupsByUserFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetEligibleSpotAwardsProgramCodesFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetExtEventMetaDataDefinitionFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetMatchedGuideLineRuleInfoFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetNewEmploymentEnabledForContingentWorkforceFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetOfferLetterTemplateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetPasswordPolicyFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetPeopleProfileHeaderFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetPermissionMetadataFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetPositionObjectDataFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetRecruitingTemplateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetRolesPermissionsFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetUserNameFormatFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetUserRolesReportFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetUsersByDynamicGroupFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetUsersPermissionsFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.GetWorkflowPendingDataFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.InitiateOnboardingFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.InitiateOnboardingForUserFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.InviteToApplyFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.IsUserEligibleForSpotAwardProgramFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.IsValidSessionFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.LogoutFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelByKeyFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelCreateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelDeleteFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelUpdateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionByKeyFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionCreateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionDeleteFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionUpdateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.ReassignJobReqFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.RefreshInterviewAssessmentsFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.RefreshMetadataFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.RejectFormFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.RejectWfRequestFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendEmailToInterviewersFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendJobReqFormToUserFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendJobReqToNextStepFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendJobReqToPreviousStepFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendMailOfferLetterFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendOfferForApprovalFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendToNextStepFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendToPreviousStepFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SendbackWfRequestFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SetSmsNotificationPreferenceFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.SignFormFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.UpdateStaticGroupFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.User;
import com.sdk.test.vdm.namespaces.sfodataedmx.UserByKeyFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.UserCreateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.UserDeleteFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.UserFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.UserUpdateFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.WithdrawWfRequestFluentHelper;
import com.sdk.test.vdm.namespaces.sfodataedmx.batch.SFODataEdmxServiceBatch;


/**
 * <h3>Details:</h3><table summary='Details'><tr><td align='right'>OData Service:</td><td>SFOData.edmx</td></tr></table>
 * 
 */
public interface SFODataEdmxService
    extends BatchService<SFODataEdmxServiceBatch>
{

    /**
     * If no other path was provided via the {@link #withServicePath(String)} method, this is the default service path used to access the endpoint.
     * 
     */
    String DEFAULT_SERVICE_PATH = "/odata/v2SFODataSet";

    /**
     * Overrides the default service path and returns a new service instance with the specified service path. Also adjusts the respective entity URLs.
     * 
     * @param servicePath
     *     Service path that will override the default.
     * @return
     *     A new service instance with the specified service path.
     */
    @Nonnull
    SFODataEdmxService withServicePath(
        @Nonnull
        final String servicePath);

    /**
     * Fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Background_CaricaPubblicaFluentHelper getAllBackground_CaricaPubblica();

    /**
     * Fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity using key fields.
     * 
     * @param backgroundElementId
     *     
     * @param userId
     *     
     * @return
     *     A fluent helper to fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Background_CaricaPubblicaByKeyFluentHelper getBackground_CaricaPubblicaByKey(final Long backgroundElementId, final String userId);

    /**
     * Create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity and save it to the S/4HANA system.
     * 
     * @param background_CaricaPubblica
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity object that will be created in the S/4HANA system.
     * @return
     *     A fluent helper to create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaCreateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Background_CaricaPubblicaCreateFluentHelper createBackground_CaricaPubblica(
        @Nonnull
        final Background_CaricaPubblica background_CaricaPubblica);

    /**
     * Update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity and save it to the S/4HANA system.
     * 
     * @param background_CaricaPubblica
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Background_CaricaPubblicaUpdateFluentHelper updateBackground_CaricaPubblica(
        @Nonnull
        final Background_CaricaPubblica background_CaricaPubblica);

    /**
     * Deletes an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity in the S/4HANA system.
     * 
     * @param background_CaricaPubblica
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A fluent helper to delete an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblicaDeleteFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    Background_CaricaPubblicaDeleteFluentHelper deleteBackground_CaricaPubblica(
        @Nonnull
        final Background_CaricaPubblica background_CaricaPubblica);

    /**
     * Fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.UserFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    UserFluentHelper getAllUser();

    /**
     * Fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity using key fields.
     * 
     * @param userId
     *     
     * @return
     *     A fluent helper to fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.UserByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    UserByKeyFluentHelper getUserByKey(final String userId);

    /**
     * Create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity and save it to the S/4HANA system.
     * 
     * @param user
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity object that will be created in the S/4HANA system.
     * @return
     *     A fluent helper to create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.UserCreateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    UserCreateFluentHelper createUser(
        @Nonnull
        final User user);

    /**
     * Update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity and save it to the S/4HANA system.
     * 
     * @param user
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.UserUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    UserUpdateFluentHelper updateUser(
        @Nonnull
        final User user);

    /**
     * Deletes an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity in the S/4HANA system.
     * 
     * @param user
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A fluent helper to delete an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.UserDeleteFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    UserDeleteFluentHelper deleteUser(
        @Nonnull
        final User user);

    /**
     * Fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistOptionFluentHelper getAllPicklistOption();

    /**
     * Fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity using key fields.
     * 
     * @param id
     *     
     * @return
     *     A fluent helper to fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistOptionByKeyFluentHelper getPicklistOptionByKey(final Long id);

    /**
     * Create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity and save it to the S/4HANA system.
     * 
     * @param picklistOption
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity object that will be created in the S/4HANA system.
     * @return
     *     A fluent helper to create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionCreateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistOptionCreateFluentHelper createPicklistOption(
        @Nonnull
        final PicklistOption picklistOption);

    /**
     * Update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity and save it to the S/4HANA system.
     * 
     * @param picklistOption
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistOptionUpdateFluentHelper updatePicklistOption(
        @Nonnull
        final PicklistOption picklistOption);

    /**
     * Deletes an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity in the S/4HANA system.
     * 
     * @param picklistOption
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A fluent helper to delete an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOptionDeleteFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistOptionDeleteFluentHelper deletePicklistOption(
        @Nonnull
        final PicklistOption picklistOption);

    /**
     * Fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entities.
     * 
     * @return
     *     A fluent helper to fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistLabelFluentHelper getAllPicklistLabel();

    /**
     * Fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity using key fields.
     * 
     * @param optionId
     *     
     * @param locale
     *     
     * @return
     *     A fluent helper to fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelByKeyFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistLabelByKeyFluentHelper getPicklistLabelByKey(final String locale, final Long optionId);

    /**
     * Create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity and save it to the S/4HANA system.
     * 
     * @param picklistLabel
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity object that will be created in the S/4HANA system.
     * @return
     *     A fluent helper to create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelCreateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistLabelCreateFluentHelper createPicklistLabel(
        @Nonnull
        final PicklistLabel picklistLabel);

    /**
     * Update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity and save it to the S/4HANA system.
     * 
     * @param picklistLabel
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity object that will be updated in the S/4HANA system.
     * @return
     *     A fluent helper to update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelUpdateFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistLabelUpdateFluentHelper updatePicklistLabel(
        @Nonnull
        final PicklistLabel picklistLabel);

    /**
     * Deletes an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity in the S/4HANA system.
     * 
     * @param picklistLabel
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity object that will be deleted in the S/4HANA system.
     * @return
     *     A fluent helper to delete an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabelDeleteFluentHelper#execute execute} method on the fluent helper object. 
     */
    @Nonnull
    PicklistLabelDeleteFluentHelper deletePicklistLabel(
        @Nonnull
        final PicklistLabel picklistLabel);

    /**
     * <p>Creates a fluent helper for the <b>refreshMetadata</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>refreshMetadata</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.RefreshMetadataFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    RefreshMetadataFluentHelper refreshMetadata();

    /**
     * Get the Matched GuideLine Rule for Users<p>Get the Matched GuideLine Rule for Users</p><p>Creates a fluent helper for the <b>getMatchedGuideLineRuleInfo</b> OData function import.</p>
     * 
     * @param level
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>level</b></p>
     * @param userIds
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userIds</b></p>
     * @param category
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>category</b></p>
     * @param programId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>programId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getMatchedGuideLineRuleInfo</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetMatchedGuideLineRuleInfoFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetMatchedGuideLineRuleInfoFluentHelper getMatchedGuideLineRuleInfo(final String programId, final String userIds, final String category, final String level);

    /**
     * Checks if a user is eligible for SpotAwardProgram<p>Checks if a user is eligible for SpotAwardProgram</p><p>Creates a fluent helper for the <b>isUserEligibleForSpotAwardProgram</b> OData function import.</p>
     * 
     * @param userId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userId</b></p>
     * @param programId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>programId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>isUserEligibleForSpotAwardProgram</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.IsUserEligibleForSpotAwardProgramFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    IsUserEligibleForSpotAwardProgramFluentHelper isUserEligibleForSpotAwardProgram(final String programId, final String userId);

    /**
     * Gets the eligible SpotAwards Program Codes<p>Gets the eligible SpotAwards Program Codes</p><p>Creates a fluent helper for the <b>getEligibleSpotAwardsProgramCodes</b> OData function import.</p>
     * 
     * @param userId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getEligibleSpotAwardsProgramCodes</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetEligibleSpotAwardsProgramCodesFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetEligibleSpotAwardsProgramCodesFluentHelper getEligibleSpotAwardsProgramCodes(final String userId);

    /**
     * <p>Creates a fluent helper for the <b>logout</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>logout</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.LogoutFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    LogoutFluentHelper logout();

    /**
     * <p>Creates a fluent helper for the <b>isValidSession</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>isValidSession</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.IsValidSessionFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    IsValidSessionFluentHelper isValidSession();

    /**
     * <p>Creates a fluent helper for the <b>checkUserPermission</b> OData function import.</p>
     * 
     * @param accessUserId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>accessUserId</b></p>
     * @param includeTBHUser
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>includeTBHUser</b></p>
     * @param permType
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>permType</b></p>
     * @param permLongValue
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>permLongValue</b></p>
     * @param permStringValue
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>permStringValue</b></p>
     * @param includeInactiveUser
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>includeInactiveUser</b></p>
     * @param targetUserId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>targetUserId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>checkUserPermission</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.CheckUserPermissionFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    CheckUserPermissionFluentHelper checkUserPermission(final String accessUserId, final String permType, final String permStringValue, final Long permLongValue, final String targetUserId, final Boolean includeInactiveUser, final Boolean includeTBHUser);

    /**
     * <p>Creates a fluent helper for the <b>updateStaticGroup</b> OData function import.</p>
     * 
     * @param groupId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>groupId</b></p>
     * @param userIds
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userIds</b></p>
     * @param action
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>action</b></p>
     * @return
     *     A fluent helper object that will execute the <b>updateStaticGroup</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.UpdateStaticGroupFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    UpdateStaticGroupFluentHelper updateStaticGroup(final Long groupId, final String action, final String userIds);

    /**
     * <p>Creates a fluent helper for the <b>getDynamicGroupsByUser</b> OData function import.</p>
     * 
     * @param groupSubType
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>groupSubType</b></p>
     * @param userId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getDynamicGroupsByUser</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetDynamicGroupsByUserFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetDynamicGroupsByUserFluentHelper getDynamicGroupsByUser(final String userId, final String groupSubType);

    /**
     * <p>Creates a fluent helper for the <b>getUsersByDynamicGroup</b> OData function import.</p>
     * 
     * @param activeOnly
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>activeOnly</b></p>
     * @param groupId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>groupId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getUsersByDynamicGroup</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetUsersByDynamicGroupFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetUsersByDynamicGroupFluentHelper getUsersByDynamicGroup(final Long groupId, final Boolean activeOnly);

    /**
     * <p>Creates a fluent helper for the <b>getUserRolesReport</b> OData function import.</p>
     * 
     * @param userIds
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userIds</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getUserRolesReport</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetUserRolesReportFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetUserRolesReportFluentHelper getUserRolesReport(final String userIds);

    /**
     * <p>Creates a fluent helper for the <b>getPermissionMetadata</b> OData function import.</p>
     * 
     * @param locale
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>locale</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getPermissionMetadata</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetPermissionMetadataFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetPermissionMetadataFluentHelper getPermissionMetadata(final String locale);

    /**
     * <p>Creates a fluent helper for the <b>getUsersPermissions</b> OData function import.</p>
     * 
     * @param userIds
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userIds</b></p>
     * @param locale
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>locale</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getUsersPermissions</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetUsersPermissionsFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetUsersPermissionsFluentHelper getUsersPermissions(final String userIds, final String locale);

    /**
     * <p>Creates a fluent helper for the <b>getRolesPermissions</b> OData function import.</p>
     * 
     * @param roleIds
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>roleIds</b></p>
     * @param locale
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>locale</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getRolesPermissions</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetRolesPermissionsFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetRolesPermissionsFluentHelper getRolesPermissions(final String roleIds, final String locale);

    /**
     * <p>Creates a fluent helper for the <b>checkUserPermissions</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>checkUserPermissions</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.CheckUserPermissionsFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    CheckUserPermissionsFluentHelper checkUserPermissions();

    /**
     * Get User Name Format<p>The function import is used to get user name format</p><p>Creates a fluent helper for the <b>getUserNameFormat</b> OData function import.</p>
     * 
     * @param locale
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>locale</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getUserNameFormat</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetUserNameFormatFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetUserNameFormatFluentHelper getUserNameFormat(final String locale);

    /**
     * Get Password Policy<p>The function import is used to get password policy</p><p>Creates a fluent helper for the <b>getPasswordPolicy</b> OData function import.</p>
     * 
     * @param locale
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>locale</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getPasswordPolicy</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetPasswordPolicyFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetPasswordPolicyFluentHelper getPasswordPolicy(final String locale);

    /**
     * Convert Assignment Id External<p>The function import is used to convert assignment id</p><p>Creates a fluent helper for the <b>convertAssignmentIdExternal</b> OData function import.</p>
     * 
     * @param newAssignmentIdExternal
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>newAssignmentIdExternal</b></p>
     * @param oldAssignmentIdExternal
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>oldAssignmentIdExternal</b></p>
     * @return
     *     A fluent helper object that will execute the <b>convertAssignmentIdExternal</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.ConvertAssignmentIdExternalFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ConvertAssignmentIdExternalFluentHelper convertAssignmentIdExternal(final String oldAssignmentIdExternal, final String newAssignmentIdExternal);

    /**
     * <p>Creates a fluent helper for the <b>getDocumentCategories</b> OData function import.</p>
     * 
     * @param entityType
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>entityType</b></p>
     * @param excludeInactive
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>excludeInactive</b></p>
     * @param enforcePerm
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>enforcePerm</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getDocumentCategories</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetDocumentCategoriesFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetDocumentCategoriesFluentHelper getDocumentCategories(final String entityType, final Boolean excludeInactive, final Boolean enforcePerm);

    /**
     * <p>Creates a fluent helper for the <b>GetBizXAction</b> OData function import.</p>
     * 
     * @param userId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userId</b></p>
     * @param actionSourceId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>actionSourceId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>GetBizXAction</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetBizXActionFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetBizXActionFluentHelper getBizXAction(final String actionSourceId, final String userId);

    /**
     * <p>Creates a fluent helper for the <b>generateNextPersonID</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>generateNextPersonID</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GenerateNextPersonIDFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GenerateNextPersonIDFluentHelper generateNextPersonID();

    /**
     * <p>Creates a fluent helper for the <b>approveWfRequest</b> OData function import.</p>
     * 
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param wfRequestId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>wfRequestId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>approveWfRequest</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.ApproveWfRequestFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ApproveWfRequestFluentHelper approveWfRequest(final Long wfRequestId, final String comment);

    /**
     * <p>Creates a fluent helper for the <b>commentWfRequest</b> OData function import.</p>
     * 
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param wfRequestId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>wfRequestId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>commentWfRequest</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.CommentWfRequestFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    CommentWfRequestFluentHelper commentWfRequest(final Long wfRequestId, final String comment);

    /**
     * <p>Creates a fluent helper for the <b>rejectWfRequest</b> OData function import.</p>
     * 
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param wfRequestId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>wfRequestId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>rejectWfRequest</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.RejectWfRequestFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    RejectWfRequestFluentHelper rejectWfRequest(final Long wfRequestId, final String comment);

    /**
     * <p>Creates a fluent helper for the <b>sendbackWfRequest</b> OData function import.</p>
     * 
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param wfRequestId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>wfRequestId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendbackWfRequest</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendbackWfRequestFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendbackWfRequestFluentHelper sendbackWfRequest(final Long wfRequestId, final String comment);

    /**
     * <p>Creates a fluent helper for the <b>withdrawWfRequest</b> OData function import.</p>
     * 
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param wfRequestId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>wfRequestId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>withdrawWfRequest</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.WithdrawWfRequestFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    WithdrawWfRequestFluentHelper withdrawWfRequest(final Long wfRequestId, final String comment);

    /**
     * <p>Creates a fluent helper for the <b>getWorkflowPendingData</b> OData function import.</p>
     * 
     * @param wfRequestId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>wfRequestId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getWorkflowPendingData</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetWorkflowPendingDataFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetWorkflowPendingDataFluentHelper getWorkflowPendingData(final Long wfRequestId);

    /**
     * <p>Creates a fluent helper for the <b>getPeopleProfileHeader</b> OData function import.</p>
     * 
     * @param userId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getPeopleProfileHeader</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetPeopleProfileHeaderFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetPeopleProfileHeaderFluentHelper getPeopleProfileHeader(final String userId);

    /**
     * Get unsupported sections of a launched form<p>sign form which is at signoff stage</p><p>Creates a fluent helper for the <b>signForm</b> OData function import.</p>
     * 
     * @param formDataId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>formDataId</b></p>
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @return
     *     A fluent helper object that will execute the <b>signForm</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SignFormFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SignFormFluentHelper signForm(final Long formDataId, final String comment);

    /**
     * reject form which is at signoff stage<p>Creates a fluent helper for the <b>rejectForm</b> OData function import.</p>
     * 
     * @param formDataId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>formDataId</b></p>
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @return
     *     A fluent helper object that will execute the <b>rejectForm</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.RejectFormFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    RejectFormFluentHelper rejectForm(final Long formDataId, final String comment);

    /**
     * Get unsupported sections of a launched form<p>send form to next step, which is at modify/reject stage</p><p>Creates a fluent helper for the <b>sendToNextStep</b> OData function import.</p>
     * 
     * @param innerStepUserId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>innerStepUserId</b></p>
     * @param formDataId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>formDataId</b></p>
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param nextIStepEntryUser
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>nextIStepEntryUser</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendToNextStep</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendToNextStepFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendToNextStepFluentHelper sendToNextStep(final Long formDataId, final String comment, final String innerStepUserId, final String nextIStepEntryUser);

    /**
     * Send form to previous step<p>send form to previous step, which is at modify stage</p><p>Creates a fluent helper for the <b>sendToPreviousStep</b> OData function import.</p>
     * 
     * @param previousIStepEntryUser
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>previousIStepEntryUser</b></p>
     * @param formDataId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>formDataId</b></p>
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendToPreviousStep</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendToPreviousStepFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendToPreviousStepFluentHelper sendToPreviousStep(final Long formDataId, final String comment, final String previousIStepEntryUser);

    /**
     * Create Performance Review Form<p>This function is used to launch PMU forms.</p><p>Creates a fluent helper for the <b>createPerformanceReviewForm</b> OData function import.</p>
     * 
     * @param formSubjectId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>formSubjectId</b></p>
     * @param sendEmail
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>sendEmail</b></p>
     * @param enRouteCopy
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>enRouteCopy</b></p>
     * @param formTemplateId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>formTemplateId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>createPerformanceReviewForm</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.CreatePerformanceReviewFormFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    CreatePerformanceReviewFormFluentHelper createPerformanceReviewForm(final String formSubjectId, final Long formTemplateId, final Boolean sendEmail, final Boolean enRouteCopy);

    /**
     * Gets position data based on the position ID<p>Reads the rule and returns a list of mapping between FieldGlass fields' name and EC position values</p><p>Creates a fluent helper for the <b>getPositionObjectData</b> OData function import.</p>
     * 
     * @param positionId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>positionId</b></p>
     * @param userId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getPositionObjectData</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetPositionObjectDataFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetPositionObjectDataFluentHelper getPositionObjectData(final Long positionId, final String userId);

    /**
     * Is New Employment Switch Enabled for CWK<p>Reads the param bean and returns true if new employment is enabled</p><p>Creates a fluent helper for the <b>getNewEmploymentEnabledForContingentWorkforce</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>getNewEmploymentEnabledForContingentWorkforce</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetNewEmploymentEnabledForContingentWorkforceFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetNewEmploymentEnabledForContingentWorkforceFluentHelper getNewEmploymentEnabledForContingentWorkforce();

    /**
     * Get Default Development Goal Plan Template Id<p>Get Default Development Goal Plan Template Id</p><p>Creates a fluent helper for the <b>getDefaultDevGoalPlanTemplateId</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>getDefaultDevGoalPlanTemplateId</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetDefaultDevGoalPlanTemplateIdFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetDefaultDevGoalPlanTemplateIdFluentHelper getDefaultDevGoalPlanTemplateId();

    /**
     * Forward Candidate to Colleague<p>Forward a candidate to colleague through e-mail</p><p>Creates a fluent helper for the <b>fwdCandidateToColleague</b> OData function import.</p>
     * 
     * @param referredTo
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>referredTo</b></p>
     * @param candidateId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>candidateId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>fwdCandidateToColleague</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.FwdCandidateToColleagueFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    FwdCandidateToColleagueFluentHelper fwdCandidateToColleague(final Long candidateId, final String referredTo);

    /**
     * Enable or disable SMS preference for Candidate<p>Use Function Import to enable/disable SMS Notifications for candidate by providing Candidate Id, Phone Country Code and Cell Phone Number</p><p>Creates a fluent helper for the <b>setSmsNotificationPreference</b> OData function import.</p>
     * 
     * @param isoCountryCode
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>isoCountryCode</b></p>
     * @param optIn
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>optIn</b></p>
     * @param candidateId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>candidateId</b></p>
     * @param cellPhone
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>cellPhone</b></p>
     * @return
     *     A fluent helper object that will execute the <b>setSmsNotificationPreference</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SetSmsNotificationPreferenceFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SetSmsNotificationPreferenceFluentHelper setSmsNotificationPreference(final Boolean optIn, final Long candidateId, final String isoCountryCode, final String cellPhone);

    /**
     * Re-assign a job requisition<p>Re-assign a job requisition</p><p>Creates a fluent helper for the <b>reassignJobReq</b> OData function import.</p>
     * 
     * @param jobReqId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>jobReqId</b></p>
     * @param coordinator
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>coordinator</b></p>
     * @param vpOfStaffing
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>vpOfStaffing</b></p>
     * @param recruiter
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>recruiter</b></p>
     * @param secondRecruiter
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>secondRecruiter</b></p>
     * @param sourcer
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>sourcer</b></p>
     * @param hiringManager
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>hiringManager</b></p>
     * @return
     *     A fluent helper object that will execute the <b>reassignJobReq</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.ReassignJobReqFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ReassignJobReqFluentHelper reassignJobReq(final Integer jobReqId, final String hiringManager, final String recruiter, final String coordinator, final String vpOfStaffing, final String secondRecruiter, final String sourcer);

    /**
     * Initiate Onboarding<p>Initiate the Onboarding process</p><p>Creates a fluent helper for the <b>initiateOnboarding</b> OData function import.</p>
     * 
     * @param applicationId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>applicationId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>initiateOnboarding</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.InitiateOnboardingFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    InitiateOnboardingFluentHelper initiateOnboarding(final Long applicationId);

    /**
     * Send a job requisition to the previous step<p>Send a job requisition to the previous step, must be performed by the "Currently With" user.</p><p>Creates a fluent helper for the <b>sendJobReqToPreviousStep</b> OData function import.</p>
     * 
     * @param jobReqId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>jobReqId</b></p>
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendJobReqToPreviousStep</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendJobReqToPreviousStepFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendJobReqToPreviousStepFluentHelper sendJobReqToPreviousStep(final Long jobReqId, final String comment);

    /**
     * Send a job requisition to the next step<p>Send a job requisition form to the next step, must be performed by the "Currently With" user.</p><p>Creates a fluent helper for the <b>sendJobReqToNextStep</b> OData function import.</p>
     * 
     * @param jobReqId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>jobReqId</b></p>
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendJobReqToNextStep</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendJobReqToNextStepFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendJobReqToNextStepFluentHelper sendJobReqToNextStep(final Long jobReqId, final String comment);

    /**
     * Send job req form to other user.<p>Send job req form to other user.</p><p>Creates a fluent helper for the <b>sendJobReqFormToUser</b> OData function import.</p>
     * 
     * @param jobReqId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>jobReqId</b></p>
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param userId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>userId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendJobReqFormToUser</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendJobReqFormToUserFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendJobReqFormToUserFluentHelper sendJobReqFormToUser(final Long jobReqId, final String userId, final String comment);

    /**
     * Approve or Decline a job requisition form<p>Updates job requisition form and approve/decline as specified by the status query parameter..</p><p>Creates a fluent helper for the <b>approveOrDeclineJobReqForm</b> OData function import.</p>
     * 
     * @param actionType
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>actionType</b></p>
     * @param jobReqId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>jobReqId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>approveOrDeclineJobReqForm</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.ApproveOrDeclineJobReqFormFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ApproveOrDeclineJobReqFormFluentHelper approveOrDeclineJobReqForm(final Long jobReqId, final String actionType);

    /**
     * Add modifier to a job requisition<p>Add modifier to a job requisition</p><p>Creates a fluent helper for the <b>addModifierToJobReq</b> OData function import.</p>
     * 
     * @param jobReqId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>jobReqId</b></p>
     * @param modifier
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>modifier</b></p>
     * @return
     *     A fluent helper object that will execute the <b>addModifierToJobReq</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.AddModifierToJobReqFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    AddModifierToJobReqFluentHelper addModifierToJobReq(final Long jobReqId, final String modifier);

    /**
     * Approve Offer<p>Approve Offer that was sent for approval.</p><p>Creates a fluent helper for the <b>approveOffer</b> OData function import.</p>
     * 
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param applicationId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>applicationId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>approveOffer</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.ApproveOfferFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    ApproveOfferFluentHelper approveOffer(final Long applicationId, final String comment);

    /**
     * Decline Offer<p>Decline Offer that was sent for approval</p><p>Creates a fluent helper for the <b>declineOffer</b> OData function import.</p>
     * 
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param applicationId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>applicationId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>declineOffer</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.DeclineOfferFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    DeclineOfferFluentHelper declineOffer(final Long applicationId, final String comment);

    /**
     * Send Offer for Approval<p>Send an Offer for approvers Approval.</p><p>Creates a fluent helper for the <b>sendOfferForApproval</b> OData function import.</p>
     * 
     * @param applicationId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>applicationId</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendOfferForApproval</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendOfferForApprovalFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendOfferForApprovalFluentHelper sendOfferForApproval(final Long applicationId);

    /**
     * Send Mail Offer Letter<p>Send an email to the candidate with offer letter.</p><p>Creates a fluent helper for the <b>sendMailOfferLetter</b> OData function import.</p>
     * 
     * @param offerLetterId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>offerLetterId</b></p>
     * @param bodyLocale
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>bodyLocale</b></p>
     * @param bodyTemplateId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>bodyTemplateId</b></p>
     * @param sendMode
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>sendMode</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendMailOfferLetter</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendMailOfferLetterFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendMailOfferLetterFluentHelper sendMailOfferLetter(final Long offerLetterId, final String sendMode, final Long bodyTemplateId, final String bodyLocale);

    /**
     * Search for rcm templates<p>Search for job requisition, job application and job offer templates .</p><p>Creates a fluent helper for the <b>getRecruitingTemplate</b> OData function import.</p>
     * 
     * @param templateType
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>templateType</b></p>
     * @param templateName
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>templateName</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getRecruitingTemplate</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetRecruitingTemplateFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetRecruitingTemplateFluentHelper getRecruitingTemplate(final String templateName, final String templateType);

    /**
     * Search for rcm offer letter templates<p>Search for offer letter templates.</p><p>Creates a fluent helper for the <b>getOfferLetterTemplate</b> OData function import.</p>
     * 
     * @param templateType
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>templateType</b></p>
     * @param templateName
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>templateName</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getOfferLetterTemplate</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetOfferLetterTemplateFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetOfferLetterTemplateFluentHelper getOfferLetterTemplate(final String templateName, final String templateType);

    /**
     * refresh Interview Assessments on updating Job Requisitions Competency<p>On adding competency to Job Requisition need to invoke refreshInterviewAssessments to update the InterviewIndividualAssessments of the Interviewers in corresponding Job Requisition.</p><p>Creates a fluent helper for the <b>refreshInterviewAssessments</b> OData function import.</p>
     * 
     * @param jobReqIdParam
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>jobReqIdParam</b></p>
     * @return
     *     A fluent helper object that will execute the <b>refreshInterviewAssessments</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.RefreshInterviewAssessmentsFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    RefreshInterviewAssessmentsFluentHelper refreshInterviewAssessments(final Long jobReqIdParam);

    /**
     * Send e-mail to interviewers<p>Send e-mail to interviewers associated with the job application.</p><p>Creates a fluent helper for the <b>sendEmailToInterviewers</b> OData function import.</p>
     * 
     * @param interviewers
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>interviewers</b></p>
     * @param attachResume
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>attachResume</b></p>
     * @param hiringManagerNote
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>hiringManagerNote</b></p>
     * @param attachCoverLetter
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>attachCoverLetter</b></p>
     * @param applicationId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>applicationId</b></p>
     * @param attachInterviewGuide
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>attachInterviewGuide</b></p>
     * @return
     *     A fluent helper object that will execute the <b>sendEmailToInterviewers</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.SendEmailToInterviewersFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    SendEmailToInterviewersFluentHelper sendEmailToInterviewers(final Long applicationId, final String interviewers, final Boolean attachResume, final Boolean attachCoverLetter, final Boolean attachInterviewGuide, final String hiringManagerNote);

    /**
     * Invite Candidates to apply for Job Requisition<p>Creates a fluent helper for the <b>inviteToApply</b> OData function import.</p>
     * 
     * @param jobReqId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>jobReqId</b></p>
     * @param candidateIds
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>candidateIds</b></p>
     * @return
     *     A fluent helper object that will execute the <b>inviteToApply</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.InviteToApplyFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    InviteToApplyFluentHelper inviteToApply(final Long jobReqId, final String candidateIds);

    /**
     * Initiate Onboarding<p>Creates a fluent helper for the <b>initiateOnboardingForUser</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>initiateOnboardingForUser</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.InitiateOnboardingForUserFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    InitiateOnboardingForUserFluentHelper initiateOnboardingForUser();

    /**
     * Get Default Goal Plan Template Id<p>Get Default Goal Plan Template Id</p><p>Creates a fluent helper for the <b>getDefaultGoalPlanTemplateId</b> OData function import.</p>
     * 
     * @return
     *     A fluent helper object that will execute the <b>getDefaultGoalPlanTemplateId</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetDefaultGoalPlanTemplateIdFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetDefaultGoalPlanTemplateIdFluentHelper getDefaultGoalPlanTemplateId();

    /**
     * Retrieve Smart Events Meta Data Definition for externally allowed events<p>Retrieve Smart Events Meta Data</p><p>Creates a fluent helper for the <b>getExtEventMetaDataDefinition</b> OData function import.</p>
     * 
     * @param topic
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>topic</b></p>
     * @param event
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>event</b></p>
     * @return
     *     A fluent helper object that will execute the <b>getExtEventMetaDataDefinition</b> OData function import with the provided parameters. To perform execution, call the {@link com.sdk.test.vdm.namespaces.sfodataedmx.GetExtEventMetaDataDefinitionFluentHelper#execute execute} method on the fluent helper object.
     */
    @Nonnull
    GetExtEventMetaDataDefinitionFluentHelper getExtEventMetaDataDefinition(final String event, final String topic);

}
