
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.BatchFluentHelperBasic;
import com.sdk.test.vdm.services.SFODataEdmxService;


/**
 * Default implementation of the {@link SFODataEdmxServiceBatch} interface exposed in the {@link com.sdk.test.vdm.services.SFODataEdmxService SFODataEdmxService}, allowing you to create multiple changesets and finally execute the batch request.
 * 
 */
public class DefaultSFODataEdmxServiceBatch
    extends BatchFluentHelperBasic<SFODataEdmxServiceBatch, SFODataEdmxServiceBatchChangeSet>
    implements SFODataEdmxServiceBatch
{

    @Nonnull
    private final SFODataEdmxService service;

    /**
     * Creates a new instance of this DefaultSFODataEdmxServiceBatch.
     * 
     * @param service
     *     The service to execute all operations in this changeset on.
     */
    public DefaultSFODataEdmxServiceBatch(
        @Nonnull
        final SFODataEdmxService service) {
        this.service = service;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected String getServicePathForBatchRequest() {
        return SFODataEdmxService.DEFAULT_SERVICE_PATH;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    protected DefaultSFODataEdmxServiceBatch getThis() {
        return this;
    }

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public SFODataEdmxServiceBatchChangeSet beginChangeSet() {
        return new DefaultSFODataEdmxServiceBatchChangeSet(this, service);
    }

}
