
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.batch;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.batch.FluentHelperBatchEndChangeSet;
import com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption;
import com.sdk.test.vdm.namespaces.sfodataedmx.User;


/**
 * This interface enables you to combine multiple operations into one change set. For further information have a look into the {@link com.sdk.test.vdm.services.SFODataEdmxService SFODataEdmxService}.
 * 
 */
public interface SFODataEdmxServiceBatchChangeSet
    extends FluentHelperBatchEndChangeSet<SFODataEdmxServiceBatch>
{


    /**
     * Create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity and save it to the S/4HANA system.
     * 
     * @param background_CaricaPubblica
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity object that will be created in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet createBackground_CaricaPubblica(
        @Nonnull
        final Background_CaricaPubblica background_CaricaPubblica);

    /**
     * Update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity and save it to the S/4HANA system.
     * 
     * @param background_CaricaPubblica
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet updateBackground_CaricaPubblica(
        @Nonnull
        final Background_CaricaPubblica background_CaricaPubblica);

    /**
     * Deletes an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity in the S/4HANA system.
     * 
     * @param background_CaricaPubblica
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity object that will be deleted in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet deleteBackground_CaricaPubblica(
        @Nonnull
        final Background_CaricaPubblica background_CaricaPubblica);

    /**
     * Create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity and save it to the S/4HANA system.
     * 
     * @param user
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity object that will be created in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet createUser(
        @Nonnull
        final User user);

    /**
     * Update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity and save it to the S/4HANA system.
     * 
     * @param user
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet updateUser(
        @Nonnull
        final User user);

    /**
     * Deletes an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity in the S/4HANA system.
     * 
     * @param user
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity object that will be deleted in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet deleteUser(
        @Nonnull
        final User user);

    /**
     * Create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity and save it to the S/4HANA system.
     * 
     * @param picklistOption
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity object that will be created in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet createPicklistOption(
        @Nonnull
        final PicklistOption picklistOption);

    /**
     * Update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity and save it to the S/4HANA system.
     * 
     * @param picklistOption
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet updatePicklistOption(
        @Nonnull
        final PicklistOption picklistOption);

    /**
     * Deletes an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity in the S/4HANA system.
     * 
     * @param picklistOption
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity object that will be deleted in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet deletePicklistOption(
        @Nonnull
        final PicklistOption picklistOption);

    /**
     * Create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity and save it to the S/4HANA system.
     * 
     * @param picklistLabel
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity object that will be created in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet createPicklistLabel(
        @Nonnull
        final PicklistLabel picklistLabel);

    /**
     * Update an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity and save it to the S/4HANA system.
     * 
     * @param picklistLabel
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity object that will be updated in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet updatePicklistLabel(
        @Nonnull
        final PicklistLabel picklistLabel);

    /**
     * Deletes an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity in the S/4HANA system.
     * 
     * @param picklistLabel
     *     {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} entity object that will be deleted in the S/4HANA system.
     * @return
     *     This fluent helper to continue adding operations to the change set. To finalize the current change set call {@link #endChangeSet endChangeSet} on the returned fluent helper object.
     */
    @Nonnull
    SFODataEdmxServiceBatchChangeSet deletePicklistLabel(
        @Nonnull
        final PicklistLabel picklistLabel);

}
