
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.batch;

import com.sap.cloud.sdk.datamodel.odata.helper.batch.FluentHelperServiceBatch;


/**
 * Interface to the batch object of an {@code com.sdk.test.vdm.services.SFODataEdmxService SFODataEdmxService} service.
 * 
 */
public interface SFODataEdmxServiceBatch
    extends FluentHelperServiceBatch<SFODataEdmxServiceBatch, SFODataEdmxServiceBatchChangeSet>
{


}
