
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica;


/**
 * Interface to enable OData entity selectors for {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica}. This interface is used by {@link com.sdk.test.vdm.namespaces.sfodataedmx.field.Background_CaricaPubblicaField Background_CaricaPubblicaField} and {@link com.sdk.test.vdm.namespaces.sfodataedmx.link.Background_CaricaPubblicaLink Background_CaricaPubblicaLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#BACKGROUND_ELEMENT_ID BACKGROUND_ELEMENT_ID}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#BG_ORDER_POS BG_ORDER_POS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#CARICA CARICA}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#END_DATE END_DATE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#ENTE ENTE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#LAST_MODIFIED_DATE LAST_MODIFIED_DATE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#START_DATE START_DATE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#UFFICIO UFFICIO}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#USER_ID USER_ID}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#TO_CARICA_NAV TO_CARICA_NAV}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#TO_ENTE_NAV TO_ENTE_NAV}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#TO_UFFICIO_NAV TO_UFFICIO_NAV}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica#TO_USER_ID_NAV TO_USER_ID_NAV}</li>
 * </ul>
 * 
 */
public interface Background_CaricaPubblicaSelectable
    extends EntitySelectable<Background_CaricaPubblica>
{


}
