
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel;


/**
 * Interface to enable OData entity selectors for {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel}. This interface is used by {@link com.sdk.test.vdm.namespaces.sfodataedmx.field.PicklistLabelField PicklistLabelField} and {@link com.sdk.test.vdm.namespaces.sfodataedmx.link.PicklistLabelLink PicklistLabelLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel#ID ID}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel#LABEL LABEL}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel#LOCALE LOCALE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel#OPTION_ID OPTION_ID}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel#TO_PICKLIST_OPTION TO_PICKLIST_OPTION}</li>
 * </ul>
 * 
 */
public interface PicklistLabelSelectable
    extends EntitySelectable<PicklistLabel>
{


}
