
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption;


/**
 * Interface to enable OData entity selectors for {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption}. This interface is used by {@link com.sdk.test.vdm.namespaces.sfodataedmx.field.PicklistOptionField PicklistOptionField} and {@link com.sdk.test.vdm.namespaces.sfodataedmx.link.PicklistOptionLink PicklistOptionLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#EXTERNAL_CODE EXTERNAL_CODE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#ID ID}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#LOCALE_LABEL LOCALE_LABEL}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#MAX_VALUE MAX_VALUE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#MDF_EXTERNAL_CODE MDF_EXTERNAL_CODE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#MIN_VALUE MIN_VALUE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#OPTION_VALUE OPTION_VALUE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#SORT_ORDER SORT_ORDER}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#STATUS STATUS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#TO_CHILD_PICKLIST_OPTIONS TO_CHILD_PICKLIST_OPTIONS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#TO_PARENT_PICKLIST_OPTION TO_PARENT_PICKLIST_OPTION}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption#TO_PICKLIST_LABELS TO_PICKLIST_LABELS}</li>
 * </ul>
 * 
 */
public interface PicklistOptionSelectable
    extends EntitySelectable<PicklistOption>
{


}
