
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sdk.test.vdm.namespaces.sfodataedmx.User;


/**
 * Interface to enable OData entity selectors for {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User}. This interface is used by {@link com.sdk.test.vdm.namespaces.sfodataedmx.field.UserField UserField} and {@link com.sdk.test.vdm.namespaces.sfodataedmx.link.UserLink UserLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#ADDRESS_LINE1 ADDRESS_LINE1}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#ADDRESS_LINE2 ADDRESS_LINE2}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#ASSUNZIONEGRUPPO ASSUNZIONEGRUPPO}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#BUSINESS_PHONE BUSINESS_PHONE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CITY CITY}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#COMPANY_EXIT_DATE COMPANY_EXIT_DATE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#COUNTRY COUNTRY}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM01 CUSTOM01}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM02 CUSTOM02}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM03 CUSTOM03}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM04 CUSTOM04}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM05 CUSTOM05}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM06 CUSTOM06}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM07 CUSTOM07}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM08 CUSTOM08}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM09 CUSTOM09}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM10 CUSTOM10}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM11 CUSTOM11}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM12 CUSTOM12}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM13 CUSTOM13}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM14 CUSTOM14}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#CUSTOM15 CUSTOM15}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#DATE_OF_BIRTH DATE_OF_BIRTH}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#DEFAULT_FULL_NAME DEFAULT_FULL_NAME}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#DEFAULT_LOCALE DEFAULT_LOCALE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#DEPARTMENT DEPARTMENT}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#DIVISION DIVISION}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#EMAIL EMAIL}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#EMP_ID EMP_ID}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#FAX FAX}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#FIRST_NAME FIRST_NAME}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#GENDER GENDER}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#HIRE_DATE HIRE_DATE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#IMPACT_OF_LOSS IMPACT_OF_LOSS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#JOB_CODE JOB_CODE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#JOB_FAMILY JOB_FAMILY}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#JOB_LEVEL JOB_LEVEL}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#JOB_ROLE JOB_ROLE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#LAST_MODIFIED LAST_MODIFIED}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#LAST_MODIFIED_DATE_TIME LAST_MODIFIED_DATE_TIME}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#LAST_MODIFIED_WITH_TZ LAST_MODIFIED_WITH_TZ}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#LAST_NAME LAST_NAME}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#LAST_REVIEW_DATE LAST_REVIEW_DATE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#LOCATION LOCATION}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#LOGIN_METHOD LOGIN_METHOD}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#MI MI}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#MINORITY MINORITY}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#ONBOARDING_ID ONBOARDING_ID}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#PASSWORD PASSWORD}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#REASON_FOR_LEAVING REASON_FOR_LEAVING}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#REVIEW_FREQ REVIEW_FREQ}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#RISK_OF_LOSS RISK_OF_LOSS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#SCI_LAST_MODIFIED SCI_LAST_MODIFIED}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#STATE STATE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#STATUS STATUS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TEAM_MEMBERS_SIZE TEAM_MEMBERS_SIZE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TIME_ZONE TIME_ZONE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TITLE TITLE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TOTAL_TEAM_SIZE TOTAL_TEAM_SIZE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#USER_ID USER_ID}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#USERNAME USERNAME}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#ZIP_CODE ZIP_CODE}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_CUSTOM_MANAGER TO_CUSTOM_MANAGER}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_CUSTOM_REPORTS TO_CUSTOM_REPORTS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_DIRECT_REPORTS TO_DIRECT_REPORTS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_HR TO_HR}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_HR_REPORTS TO_HR_REPORTS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_IMPACT_OF_LOSS_NAV TO_IMPACT_OF_LOSS_NAV}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_MANAGER TO_MANAGER}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_MATRIX_MANAGER TO_MATRIX_MANAGER}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_MATRIX_REPORTS TO_MATRIX_REPORTS}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_PROXY TO_PROXY}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_REASON_FOR_LEAVING_NAV TO_REASON_FOR_LEAVING_NAV}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_RISK_OF_LOSS_NAV TO_RISK_OF_LOSS_NAV}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_SECOND_MANAGER TO_SECOND_MANAGER}</li>
 * <li>{@link com.sdk.test.vdm.namespaces.sfodataedmx.User#TO_SECOND_REPORTS TO_SECOND_REPORTS}</li>
 * </ul>
 * 
 */
public interface UserSelectable
    extends EntitySelectable<User>
{


}
