
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.net.URI;
import java.util.List;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.google.common.collect.Maps;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestinationProperties;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperFunction;
import com.sap.cloud.sdk.datamodel.odata.helper.ODataTypeValueSerializer;
import com.sap.cloud.sdk.odatav2.connectivity.ODataException;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.olingo.odata2.api.edm.EdmSimpleTypeKind;


/**
 * Fluent helper for the <b>approveWfRequest</b> OData function import.
 * 
 */
public class ApproveWfRequestFluentHelper
    extends FluentHelperFunction<ApproveWfRequestFluentHelper, WfRequestActionResponse, List<WfRequestActionResponse>>
{

    private final Map<String, Object> values = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will execute the <b>approveWfRequest</b> OData function import with the provided parameters. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to call the functions against.
     * @param comment
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>comment</b></p>
     * @param wfRequestId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>wfRequestId</b></p>
     */
    public ApproveWfRequestFluentHelper(
        @Nonnull
        final String servicePath, final Long wfRequestId, final String comment) {
        super(servicePath);
        values.put("wfRequestId", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Int64).toUri(wfRequestId));
        values.put("comment", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(comment));
    }

    @Override
    @Nonnull
    protected Class<WfRequestActionResponse> getEntityClass() {
        return WfRequestActionResponse.class;
    }

    @Override
    @Nonnull
    protected String getFunctionName() {
        return "approveWfRequest";
    }

    @Override
    @Nullable
    protected JsonElement refineJsonResponse(
        @Nullable
        JsonElement jsonElement) {
        if ((jsonElement instanceof JsonObject)&&((JsonObject) jsonElement).has(getFunctionName())) {
            jsonElement = ((JsonObject) jsonElement).get(getFunctionName());
        }
        return super.refineJsonResponse(jsonElement);
    }

    @Override
    @Nonnull
    protected Map<String, Object> getParameters() {
        return values;
    }

    @Override
    @Nonnull
    protected HttpUriRequest createRequest(
        @Nonnull
        final URI uri) {
        return new HttpPost(uri);
    }

    @Override
    @Nonnull
    public List<WfRequestActionResponse> execute(
        @Nonnull
        final HttpDestinationProperties destination)
        throws ODataException
    {
        return super.executeMultiple(destination);
    }

}
