
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;
import com.sdk.test.vdm.namespaces.sfodataedmx.selectable.Background_CaricaPubblicaSelectable;


/**
 * Fluent helper to fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class Background_CaricaPubblicaByKeyFluentHelper
    extends FluentHelperByKey<Background_CaricaPubblicaByKeyFluentHelper, Background_CaricaPubblica, Background_CaricaPubblicaSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity with the provided key field values. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to fetch a single {@code Background_CaricaPubblica}
     * @param backgroundElementId
     *     
     * @param userId
     *     
     */
    public Background_CaricaPubblicaByKeyFluentHelper(
        @Nonnull
        final String servicePath, final Long backgroundElementId, final String userId) {
        super(servicePath);
        this.key.put("backgroundElementId", backgroundElementId);
        this.key.put("userId", userId);
    }

    @Override
    @Nonnull
    protected Class<Background_CaricaPubblica> getEntityClass() {
        return Background_CaricaPubblica.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
