
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperCreate;


/**
 * Fluent helper to create a new {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity and save it to the S/4HANA system.<p>
 * To perform execution, call the {@link #execute execute} method on the fluent helper object.
 * 
 */
public class Background_CaricaPubblicaCreateFluentHelper
    extends FluentHelperCreate<Background_CaricaPubblicaCreateFluentHelper, Background_CaricaPubblica>
{

    /**
     * {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity object that will be created in the S/4HANA system.
     * 
     */
    private final Background_CaricaPubblica entity;

    /**
     * Creates a fluent helper object that will create a {@link com.sdk.test.vdm.namespaces.sfodataedmx.Background_CaricaPubblica Background_CaricaPubblica} entity on the OData endpoint. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     The service path to direct the create requests to.
     * @param entity
     *     The Background_CaricaPubblica to create.
     */
    public Background_CaricaPubblicaCreateFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final Background_CaricaPubblica entity) {
        super(servicePath);
        this.entity = entity;
    }

    @Override
    @Nonnull
    protected Background_CaricaPubblica getEntity() {
        return entity;
    }

}
