
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>ChangeDataBean</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class ChangeDataBean
    extends VdmComplex<ChangeDataBean>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>label</b></p>
     * 
     * @param label
     *     
     */
    @SerializedName("label")
    @JsonProperty("label")
    @Nullable
    @ODataField(odataName = "label")
    private String label;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>newValue</b></p>
     * 
     * @param newValue
     *     
     */
    @SerializedName("newValue")
    @JsonProperty("newValue")
    @Nullable
    @ODataField(odataName = "newValue")
    private String newValue;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>oldValue</b></p>
     * 
     * @param oldValue
     *     
     */
    @SerializedName("oldValue")
    @JsonProperty("oldValue")
    @Nullable
    @ODataField(odataName = "oldValue")
    private String oldValue;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<ChangeDataBean> getType() {
        return ChangeDataBean.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("label", getLabel());
        values.put("newValue", getNewValue());
        values.put("oldValue", getOldValue());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("label")) {
                final Object value = values.remove("label");
                if ((value == null)||(!value.equals(getLabel()))) {
                    setLabel(((String) value));
                }
            }
            if (values.containsKey("newValue")) {
                final Object value = values.remove("newValue");
                if ((value == null)||(!value.equals(getNewValue()))) {
                    setNewValue(((String) value));
                }
            }
            if (values.containsKey("oldValue")) {
                final Object value = values.remove("oldValue");
                if ((value == null)||(!value.equals(getOldValue()))) {
                    setOldValue(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
