
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * CORouteFormStatusBean<p>identify if form is successfully signed/rejected/sent to next step</p><p>Original complex type name from the Odata EDM: <b>CORouteFormStatusBean</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class CORouteFormStatusBean
    extends VdmComplex<CORouteFormStatusBean>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>redirectUrl</b></p>
     * 
     * @param redirectUrl
     *     
     */
    @SerializedName("redirectUrl")
    @JsonProperty("redirectUrl")
    @Nullable
    @ODataField(odataName = "redirectUrl")
    private String redirectUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>status</b></p>
     * 
     * @param status
     *     
     */
    @SerializedName("status")
    @JsonProperty("status")
    @Nullable
    @ODataField(odataName = "status")
    private String status;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<CORouteFormStatusBean> getType() {
        return CORouteFormStatusBean.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("redirectUrl", getRedirectUrl());
        values.put("status", getStatus());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("redirectUrl")) {
                final Object value = values.remove("redirectUrl");
                if ((value == null)||(!value.equals(getRedirectUrl()))) {
                    setRedirectUrl(((String) value));
                }
            }
            if (values.containsKey("status")) {
                final Object value = values.remove("status");
                if ((value == null)||(!value.equals(getStatus()))) {
                    setStatus(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
