
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>COUserInfoElementBean</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class COUserInfoElementBean
    extends VdmComplex<COUserInfoElementBean>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>id</b></p>
     * 
     * @param id
     *     
     */
    @SerializedName("id")
    @JsonProperty("id")
    @Nullable
    @ODataField(odataName = "id")
    private String id;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>label</b></p>
     * 
     * @param label
     *     
     */
    @SerializedName("label")
    @JsonProperty("label")
    @Nullable
    @ODataField(odataName = "label")
    private String label;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>type</b></p>
     * 
     * @param type_2
     *     
     */
    @SerializedName("type")
    @JsonProperty("type")
    @Nullable
    @ODataField(odataName = "type")
    private String type_2;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>value</b></p>
     * 
     * @param value
     *     
     */
    @SerializedName("value")
    @JsonProperty("value")
    @Nullable
    @ODataField(odataName = "value")
    private String value;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<COUserInfoElementBean> getType() {
        return COUserInfoElementBean.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("id", getId());
        values.put("label", getLabel());
        values.put("type", getType_2());
        values.put("value", getValue());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("id")) {
                final Object value = values.remove("id");
                if ((value == null)||(!value.equals(getId()))) {
                    setId(((String) value));
                }
            }
            if (values.containsKey("label")) {
                final Object value = values.remove("label");
                if ((value == null)||(!value.equals(getLabel()))) {
                    setLabel(((String) value));
                }
            }
            if (values.containsKey("type")) {
                final Object value = values.remove("type");
                if ((value == null)||(!value.equals(getType_2()))) {
                    setType_2(((String) value));
                }
            }
            if (values.containsKey("value")) {
                final Object value = values.remove("value");
                if ((value == null)||(!value.equals(getValue()))) {
                    setValue(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
