
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * CreatePMFormResponse<p>This is response object for launch performance review form action</p><p>Original complex type name from the Odata EDM: <b>CreatePerformanceReviewFormResponse</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class CreatePerformanceReviewFormResponse
    extends VdmComplex<CreatePerformanceReviewFormResponse>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>formDataId</b></p>
     * 
     * @param formDataId
     *     
     */
    @SerializedName("formDataId")
    @JsonProperty("formDataId")
    @Nullable
    @ODataField(odataName = "formDataId")
    private Long formDataId;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>status</b></p>
     * 
     * @param status
     *     
     */
    @SerializedName("status")
    @JsonProperty("status")
    @Nullable
    @ODataField(odataName = "status")
    private String status;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>statusCode</b></p>
     * 
     * @param statusCode
     *     
     */
    @SerializedName("statusCode")
    @JsonProperty("statusCode")
    @Nullable
    @ODataField(odataName = "statusCode")
    private Long statusCode;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<CreatePerformanceReviewFormResponse> getType() {
        return CreatePerformanceReviewFormResponse.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("formDataId", getFormDataId());
        values.put("status", getStatus());
        values.put("statusCode", getStatusCode());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("formDataId")) {
                final Object value = values.remove("formDataId");
                if ((value == null)||(!value.equals(getFormDataId()))) {
                    setFormDataId(((Long) value));
                }
            }
            if (values.containsKey("status")) {
                final Object value = values.remove("status");
                if ((value == null)||(!value.equals(getStatus()))) {
                    setStatus(((String) value));
                }
            }
            if (values.containsKey("statusCode")) {
                final Object value = values.remove("statusCode");
                if ((value == null)||(!value.equals(getStatusCode()))) {
                    setStatusCode(((Long) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
