
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>DocumentCategories</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class DocumentCategories
    extends VdmComplex<DocumentCategories>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>attachmemtCategories</b></p>
     * 
     * @param attachmemtCategories
     *     
     */
    @SerializedName("attachmemtCategories")
    @JsonProperty("attachmemtCategories")
    @Nullable
    @ODataField(odataName = "attachmemtCategories")
    private DocumentCategoryDetails attachmemtCategories;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<DocumentCategories> getType() {
        return DocumentCategories.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("attachmemtCategories", getAttachmemtCategories());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
        }
        // structured properties
        {
            if (values.containsKey("attachmemtCategories")) {
                final Object value = values.remove("attachmemtCategories");
                if (value instanceof Map) {
                    if (getAttachmemtCategories() == null) {
                        setAttachmemtCategories(new DocumentCategoryDetails());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getAttachmemtCategories().fromMap(inputMap);
                }
                if ((value == null)&&(getAttachmemtCategories()!= null)) {
                    setAttachmemtCategories(null);
                }
            }
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
