
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>GetBizXActionResponse</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class GetBizXActionResponse
    extends VdmComplex<GetBizXActionResponse>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>actionId</b></p>
     * 
     * @param actionId
     *     
     */
    @SerializedName("actionId")
    @JsonProperty("actionId")
    @Nullable
    @ODataField(odataName = "actionId")
    private String actionId;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>actionLabel</b></p>
     * 
     * @param actionLabel
     *     
     */
    @SerializedName("actionLabel")
    @JsonProperty("actionLabel")
    @Nullable
    @ODataField(odataName = "actionLabel")
    private String actionLabel;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>deepLinkUrl</b></p>
     * 
     * @param deepLinkUrl
     *     
     */
    @SerializedName("deepLinkUrl")
    @JsonProperty("deepLinkUrl")
    @Nullable
    @ODataField(odataName = "deepLinkUrl")
    private String deepLinkUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>userId</b></p>
     * 
     * @param userId
     *     
     */
    @SerializedName("userId")
    @JsonProperty("userId")
    @Nullable
    @ODataField(odataName = "userId")
    private String userId;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<GetBizXActionResponse> getType() {
        return GetBizXActionResponse.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("actionId", getActionId());
        values.put("actionLabel", getActionLabel());
        values.put("deepLinkUrl", getDeepLinkUrl());
        values.put("userId", getUserId());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("actionId")) {
                final Object value = values.remove("actionId");
                if ((value == null)||(!value.equals(getActionId()))) {
                    setActionId(((String) value));
                }
            }
            if (values.containsKey("actionLabel")) {
                final Object value = values.remove("actionLabel");
                if ((value == null)||(!value.equals(getActionLabel()))) {
                    setActionLabel(((String) value));
                }
            }
            if (values.containsKey("deepLinkUrl")) {
                final Object value = values.remove("deepLinkUrl");
                if ((value == null)||(!value.equals(getDeepLinkUrl()))) {
                    setDeepLinkUrl(((String) value));
                }
            }
            if (values.containsKey("userId")) {
                final Object value = values.remove("userId");
                if ((value == null)||(!value.equals(getUserId()))) {
                    setUserId(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
