
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.net.URI;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.google.common.collect.Maps;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestinationProperties;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperFunction;
import com.sap.cloud.sdk.datamodel.odata.helper.ODataTypeValueSerializer;
import com.sap.cloud.sdk.odatav2.connectivity.ODataException;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.olingo.odata2.api.edm.EdmSimpleTypeKind;


/**
 * Fluent helper for the <b>getExtEventMetaDataDefinition</b> OData function import.
 * 
 */
public class GetExtEventMetaDataDefinitionFluentHelper
    extends FluentHelperFunction<GetExtEventMetaDataDefinitionFluentHelper, SEFExtEventMetaDataList, SEFExtEventMetaDataList>
{

    private final Map<String, Object> values = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will execute the <b>getExtEventMetaDataDefinition</b> OData function import with the provided parameters. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to call the functions against.
     * @param topic
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>topic</b></p>
     * @param event
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>event</b></p>
     */
    public GetExtEventMetaDataDefinitionFluentHelper(
        @Nonnull
        final String servicePath, final String event, final String topic) {
        super(servicePath);
        values.put("event", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(event));
        values.put("topic", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(topic));
    }

    @Override
    @Nonnull
    protected Class<SEFExtEventMetaDataList> getEntityClass() {
        return SEFExtEventMetaDataList.class;
    }

    @Override
    @Nonnull
    protected String getFunctionName() {
        return "getExtEventMetaDataDefinition";
    }

    @Override
    @Nullable
    protected JsonElement refineJsonResponse(
        @Nullable
        JsonElement jsonElement) {
        if ((jsonElement instanceof JsonObject)&&((JsonObject) jsonElement).has(getFunctionName())) {
            jsonElement = ((JsonObject) jsonElement).get(getFunctionName());
        }
        return super.refineJsonResponse(jsonElement);
    }

    @Override
    @Nonnull
    protected Map<String, Object> getParameters() {
        return values;
    }

    @Override
    @Nonnull
    protected HttpUriRequest createRequest(
        @Nonnull
        final URI uri) {
        return new HttpGet(uri);
    }

    @Override
    @Nullable
    public SEFExtEventMetaDataList execute(
        @Nonnull
        final HttpDestinationProperties destination)
        throws ODataException
    {
        return super.executeSingle(destination);
    }

}
