
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>map_entry_string_string_</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class map_entry_string_string_
    extends VdmComplex<map_entry_string_string_>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>key</b></p>
     * 
     * @param key_2
     *     
     */
    @SerializedName("key")
    @JsonProperty("key")
    @Nullable
    @ODataField(odataName = "key")
    private String key_2;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>value</b></p>
     * 
     * @param value
     *     
     */
    @SerializedName("value")
    @JsonProperty("value")
    @Nullable
    @ODataField(odataName = "value")
    private String value;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<map_entry_string_string_> getType() {
        return map_entry_string_string_.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("key", getKey_2());
        values.put("value", getValue());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("key")) {
                final Object value = values.remove("key");
                if ((value == null)||(!value.equals(getKey_2()))) {
                    setKey_2(((String) value));
                }
            }
            if (values.containsKey("value")) {
                final Object value = values.remove("value");
                if ((value == null)||(!value.equals(getValue()))) {
                    setValue(((String) value));
                }
            }
        }
        // structured properties
        {
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
