
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>PendDataGroupBean</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class PendDataGroupBean
    extends VdmComplex<PendDataGroupBean>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>changeSet</b></p>
     * 
     * @param changeSet
     *     
     */
    @SerializedName("changeSet")
    @JsonProperty("changeSet")
    @Nullable
    @ODataField(odataName = "changeSet")
    private EssMssWorkflowAttributeBean changeSet;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>inlineGroups</b></p>
     * 
     * @param inlineGroups
     *     
     */
    @SerializedName("inlineGroups")
    @JsonProperty("inlineGroups")
    @Nullable
    @ODataField(odataName = "inlineGroups")
    private PendDataInlineGroupBean inlineGroups;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>subChangeSetGroups</b></p>
     * 
     * @param subChangeSetGroups
     *     
     */
    @SerializedName("subChangeSetGroups")
    @JsonProperty("subChangeSetGroups")
    @Nullable
    @ODataField(odataName = "subChangeSetGroups")
    private EssMssWorkflowSubAttributeBean subChangeSetGroups;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>title</b></p>
     * 
     * @param title
     *     
     */
    @SerializedName("title")
    @JsonProperty("title")
    @Nullable
    @ODataField(odataName = "title")
    private String title;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<PendDataGroupBean> getType() {
        return PendDataGroupBean.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("changeSet", getChangeSet());
        values.put("inlineGroups", getInlineGroups());
        values.put("subChangeSetGroups", getSubChangeSetGroups());
        values.put("title", getTitle());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("title")) {
                final Object value = values.remove("title");
                if ((value == null)||(!value.equals(getTitle()))) {
                    setTitle(((String) value));
                }
            }
        }
        // structured properties
        {
            if (values.containsKey("changeSet")) {
                final Object value = values.remove("changeSet");
                if (value instanceof Map) {
                    if (getChangeSet() == null) {
                        setChangeSet(new EssMssWorkflowAttributeBean());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getChangeSet().fromMap(inputMap);
                }
                if ((value == null)&&(getChangeSet()!= null)) {
                    setChangeSet(null);
                }
            }
            if (values.containsKey("inlineGroups")) {
                final Object value = values.remove("inlineGroups");
                if (value instanceof Map) {
                    if (getInlineGroups() == null) {
                        setInlineGroups(new PendDataInlineGroupBean());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getInlineGroups().fromMap(inputMap);
                }
                if ((value == null)&&(getInlineGroups()!= null)) {
                    setInlineGroups(null);
                }
            }
            if (values.containsKey("subChangeSetGroups")) {
                final Object value = values.remove("subChangeSetGroups");
                if (value instanceof Map) {
                    if (getSubChangeSetGroups() == null) {
                        setSubChangeSetGroups(new EssMssWorkflowSubAttributeBean());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getSubChangeSetGroups().fromMap(inputMap);
                }
                if ((value == null)&&(getSubChangeSetGroups()!= null)) {
                    setSubChangeSetGroups(null);
                }
            }
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
