
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>PeopleProfileHeaderResponse</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class PeopleProfileHeaderResponse
    extends VdmComplex<PeopleProfileHeaderResponse>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>aboutMeVideoDeleteUrl</b></p>
     * 
     * @param aboutMeVideoDeleteUrl
     *     
     */
    @SerializedName("aboutMeVideoDeleteUrl")
    @JsonProperty("aboutMeVideoDeleteUrl")
    @Nullable
    @ODataField(odataName = "aboutMeVideoDeleteUrl")
    private String aboutMeVideoDeleteUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>aboutMeVideoEnabled</b></p>
     * 
     * @param aboutMeVideoEnabled
     *     
     */
    @SerializedName("aboutMeVideoEnabled")
    @JsonProperty("aboutMeVideoEnabled")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "aboutMeVideoEnabled")
    private Boolean aboutMeVideoEnabled;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>aboutMeVideoGetFileUrl</b></p>
     * 
     * @param aboutMeVideoGetFileUrl
     *     
     */
    @SerializedName("aboutMeVideoGetFileUrl")
    @JsonProperty("aboutMeVideoGetFileUrl")
    @Nullable
    @ODataField(odataName = "aboutMeVideoGetFileUrl")
    private String aboutMeVideoGetFileUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>aboutMeVideoStatusUrl</b></p>
     * 
     * @param aboutMeVideoStatusUrl
     *     
     */
    @SerializedName("aboutMeVideoStatusUrl")
    @JsonProperty("aboutMeVideoStatusUrl")
    @Nullable
    @ODataField(odataName = "aboutMeVideoStatusUrl")
    private String aboutMeVideoStatusUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>aboutMeVideoToken</b></p>
     * 
     * @param aboutMeVideoToken
     *     
     */
    @SerializedName("aboutMeVideoToken")
    @JsonProperty("aboutMeVideoToken")
    @Nullable
    @ODataField(odataName = "aboutMeVideoToken")
    private String aboutMeVideoToken;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>aboutMeVideoUploadId</b></p>
     * 
     * @param aboutMeVideoUploadId
     *     
     */
    @SerializedName("aboutMeVideoUploadId")
    @JsonProperty("aboutMeVideoUploadId")
    @Nullable
    @ODataField(odataName = "aboutMeVideoUploadId")
    private String aboutMeVideoUploadId;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>aboutMeVideoUploadUrl</b></p>
     * 
     * @param aboutMeVideoUploadUrl
     *     
     */
    @SerializedName("aboutMeVideoUploadUrl")
    @JsonProperty("aboutMeVideoUploadUrl")
    @Nullable
    @ODataField(odataName = "aboutMeVideoUploadUrl")
    private String aboutMeVideoUploadUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>applicationId</b></p>
     * 
     * @param applicationId
     *     
     */
    @SerializedName("applicationId")
    @JsonProperty("applicationId")
    @Nullable
    @ODataField(odataName = "applicationId")
    private String applicationId;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>businessPhone</b></p>
     * 
     * @param businessPhone
     *     
     */
    @SerializedName("businessPhone")
    @JsonProperty("businessPhone")
    @Nullable
    @ODataField(odataName = "businessPhone")
    private String businessPhone;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>cellPhone</b></p>
     * 
     * @param cellPhone
     *     
     */
    @SerializedName("cellPhone")
    @JsonProperty("cellPhone")
    @Nullable
    @ODataField(odataName = "cellPhone")
    private String cellPhone;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>customFields</b></p>
     * 
     * @param customFields_2
     *     
     */
    @SerializedName("customFields")
    @JsonProperty("customFields")
    @Nullable
    @ODataField(odataName = "customFields")
    private COUserInfoElementBean customFields_2;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>dSTSavings</b></p>
     * 
     * @param dSTSavings
     *     
     */
    @SerializedName("dSTSavings")
    @JsonProperty("dSTSavings")
    @Nullable
    @ODataField(odataName = "dSTSavings")
    private Integer dSTSavings;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>department</b></p>
     * 
     * @param department
     *     
     */
    @SerializedName("department")
    @JsonProperty("department")
    @Nullable
    @ODataField(odataName = "department")
    private String department;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>division</b></p>
     * 
     * @param division
     *     
     */
    @SerializedName("division")
    @JsonProperty("division")
    @Nullable
    @ODataField(odataName = "division")
    private String division;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>email</b></p>
     * 
     * @param email
     *     
     */
    @SerializedName("email")
    @JsonProperty("email")
    @Nullable
    @ODataField(odataName = "email")
    private String email;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>expressivePhotoMod</b></p>
     * 
     * @param expressivePhotoMod
     *     
     */
    @SerializedName("expressivePhotoMod")
    @JsonProperty("expressivePhotoMod")
    @Nullable
    @ODataField(odataName = "expressivePhotoMod")
    private String expressivePhotoMod;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>fullName</b></p>
     * 
     * @param fullName
     *     
     */
    @SerializedName("fullName")
    @JsonProperty("fullName")
    @Nullable
    @ODataField(odataName = "fullName")
    private String fullName;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>introduction</b></p>
     * 
     * @param introduction
     *     
     */
    @SerializedName("introduction")
    @JsonProperty("introduction")
    @Nullable
    @ODataField(odataName = "introduction")
    private String introduction;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>isAboutMeTextEnabled</b></p>
     * 
     * @param isAboutMeTextEnabled
     *     
     */
    @SerializedName("isAboutMeTextEnabled")
    @JsonProperty("isAboutMeTextEnabled")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "isAboutMeTextEnabled")
    private Boolean isAboutMeTextEnabled;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>isAllowUploadBGPhoto</b></p>
     * 
     * @param isAllowUploadBGPhoto
     *     
     */
    @SerializedName("isAllowUploadBGPhoto")
    @JsonProperty("isAllowUploadBGPhoto")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "isAllowUploadBGPhoto")
    private Boolean isAllowUploadBGPhoto;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>isPercentCompleteEnabled</b></p>
     * 
     * @param isPercentCompleteEnabled
     *     
     */
    @SerializedName("isPercentCompleteEnabled")
    @JsonProperty("isPercentCompleteEnabled")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "isPercentCompleteEnabled")
    private Boolean isPercentCompleteEnabled;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>isShowAsOfDate</b></p>
     * 
     * @param isShowAsOfDate
     *     
     */
    @SerializedName("isShowAsOfDate")
    @JsonProperty("isShowAsOfDate")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "isShowAsOfDate")
    private Boolean isShowAsOfDate;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>isShowEditLink</b></p>
     * 
     * @param isShowEditLink
     *     
     */
    @SerializedName("isShowEditLink")
    @JsonProperty("isShowEditLink")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "isShowEditLink")
    private Boolean isShowEditLink;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>isTimeZoneInDaylightTime</b></p>
     * 
     * @param isTimeZoneInDaylightTime
     *     
     */
    @SerializedName("isTimeZoneInDaylightTime")
    @JsonProperty("isTimeZoneInDaylightTime")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "isTimeZoneInDaylightTime")
    private Boolean isTimeZoneInDaylightTime;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>liveProfileOriginalPhotoId</b></p>
     * 
     * @param liveProfileOriginalPhotoId
     *     
     */
    @SerializedName("liveProfileOriginalPhotoId")
    @JsonProperty("liveProfileOriginalPhotoId")
    @Nullable
    @ODataField(odataName = "liveProfileOriginalPhotoId")
    private Long liveProfileOriginalPhotoId;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>liveProfilePhotoId</b></p>
     * 
     * @param liveProfilePhotoId
     *     
     */
    @SerializedName("liveProfilePhotoId")
    @JsonProperty("liveProfilePhotoId")
    @Nullable
    @ODataField(odataName = "liveProfilePhotoId")
    private Long liveProfilePhotoId;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>liveProfilePhotoMod</b></p>
     * 
     * @param liveProfilePhotoMod
     *     
     */
    @SerializedName("liveProfilePhotoMod")
    @JsonProperty("liveProfilePhotoMod")
    @Nullable
    @ODataField(odataName = "liveProfilePhotoMod")
    private String liveProfilePhotoMod;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>localTimeEnabled</b></p>
     * 
     * @param localTimeEnabled
     *     
     */
    @SerializedName("localTimeEnabled")
    @JsonProperty("localTimeEnabled")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "localTimeEnabled")
    private Boolean localTimeEnabled;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>location</b></p>
     * 
     * @param location
     *     
     */
    @SerializedName("location")
    @JsonProperty("location")
    @Nullable
    @ODataField(odataName = "location")
    private String location;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>mediaServiceBaseUrl</b></p>
     * 
     * @param mediaServiceBaseUrl
     *     
     */
    @SerializedName("mediaServiceBaseUrl")
    @JsonProperty("mediaServiceBaseUrl")
    @Nullable
    @ODataField(odataName = "mediaServiceBaseUrl")
    private String mediaServiceBaseUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>myNameAudioDeleteUrl</b></p>
     * 
     * @param myNameAudioDeleteUrl
     *     
     */
    @SerializedName("myNameAudioDeleteUrl")
    @JsonProperty("myNameAudioDeleteUrl")
    @Nullable
    @ODataField(odataName = "myNameAudioDeleteUrl")
    private String myNameAudioDeleteUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>myNameAudioGetFileUrl</b></p>
     * 
     * @param myNameAudioGetFileUrl
     *     
     */
    @SerializedName("myNameAudioGetFileUrl")
    @JsonProperty("myNameAudioGetFileUrl")
    @Nullable
    @ODataField(odataName = "myNameAudioGetFileUrl")
    private String myNameAudioGetFileUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>myNameAudioStatusUrl</b></p>
     * 
     * @param myNameAudioStatusUrl
     *     
     */
    @SerializedName("myNameAudioStatusUrl")
    @JsonProperty("myNameAudioStatusUrl")
    @Nullable
    @ODataField(odataName = "myNameAudioStatusUrl")
    private String myNameAudioStatusUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>myNameAudioUploadUrl</b></p>
     * 
     * @param myNameAudioUploadUrl
     *     
     */
    @SerializedName("myNameAudioUploadUrl")
    @JsonProperty("myNameAudioUploadUrl")
    @Nullable
    @ODataField(odataName = "myNameAudioUploadUrl")
    private String myNameAudioUploadUrl;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>myNameEnabled</b></p>
     * 
     * @param myNameEnabled
     *     
     */
    @SerializedName("myNameEnabled")
    @JsonProperty("myNameEnabled")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "myNameEnabled")
    private Boolean myNameEnabled;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>myNameText</b></p>
     * 
     * @param myNameText
     *     
     */
    @SerializedName("myNameText")
    @JsonProperty("myNameText")
    @Nullable
    @ODataField(odataName = "myNameText")
    private String myNameText;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>myNameToken</b></p>
     * 
     * @param myNameToken
     *     
     */
    @SerializedName("myNameToken")
    @JsonProperty("myNameToken")
    @Nullable
    @ODataField(odataName = "myNameToken")
    private String myNameToken;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>myNameUploadId</b></p>
     * 
     * @param myNameUploadId
     *     
     */
    @SerializedName("myNameUploadId")
    @JsonProperty("myNameUploadId")
    @Nullable
    @ODataField(odataName = "myNameUploadId")
    private String myNameUploadId;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>phoneNumbers</b></p>
     * 
     * @param phoneNumbers
     *     
     */
    @SerializedName("phoneNumbers")
    @JsonProperty("phoneNumbers")
    @Nullable
    @ODataField(odataName = "phoneNumbers")
    private COUserInfoElementBean phoneNumbers;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>showLiveProfilePhoto</b></p>
     * 
     * @param showLiveProfilePhoto
     *     
     */
    @SerializedName("showLiveProfilePhoto")
    @JsonProperty("showLiveProfilePhoto")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "showLiveProfilePhoto")
    private Boolean showLiveProfilePhoto;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>socialAccounts</b></p>
     * 
     * @param socialAccounts
     *     
     */
    @SerializedName("socialAccounts")
    @JsonProperty("socialAccounts")
    @Nullable
    @ODataField(odataName = "socialAccounts")
    private COSocialAccountBean socialAccounts;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>socialNetworks</b></p>
     * 
     * @param socialNetworks
     *     
     */
    @SerializedName("socialNetworks")
    @JsonProperty("socialNetworks")
    @Nullable
    @ODataField(odataName = "socialNetworks")
    private COUserInfoElementBean socialNetworks;
    /**
     * Constraints: Not nullable<p>Original property from the Odata EDM: <b>targetUserId</b></p>
     * 
     * @param targetUserId
     *     
     */
    @SerializedName("targetUserId")
    @JsonProperty("targetUserId")
    @Nullable
    @ODataField(odataName = "targetUserId")
    private String targetUserId;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>timezone</b></p>
     * 
     * @param timezone
     *     
     */
    @SerializedName("timezone")
    @JsonProperty("timezone")
    @Nullable
    @ODataField(odataName = "timezone")
    private String timezone;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>title</b></p>
     * 
     * @param title
     *     
     */
    @SerializedName("title")
    @JsonProperty("title")
    @Nullable
    @ODataField(odataName = "title")
    private String title;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>userName</b></p>
     * 
     * @param userName
     *     
     */
    @SerializedName("userName")
    @JsonProperty("userName")
    @Nullable
    @ODataField(odataName = "userName")
    private String userName;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>utcOffset</b></p>
     * 
     * @param utcOffset
     *     
     */
    @SerializedName("utcOffset")
    @JsonProperty("utcOffset")
    @Nullable
    @ODataField(odataName = "utcOffset")
    private Integer utcOffset;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<PeopleProfileHeaderResponse> getType() {
        return PeopleProfileHeaderResponse.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("aboutMeVideoDeleteUrl", getAboutMeVideoDeleteUrl());
        values.put("aboutMeVideoEnabled", getAboutMeVideoEnabled());
        values.put("aboutMeVideoGetFileUrl", getAboutMeVideoGetFileUrl());
        values.put("aboutMeVideoStatusUrl", getAboutMeVideoStatusUrl());
        values.put("aboutMeVideoToken", getAboutMeVideoToken());
        values.put("aboutMeVideoUploadId", getAboutMeVideoUploadId());
        values.put("aboutMeVideoUploadUrl", getAboutMeVideoUploadUrl());
        values.put("applicationId", getApplicationId());
        values.put("businessPhone", getBusinessPhone());
        values.put("cellPhone", getCellPhone());
        values.put("customFields", getCustomFields_2());
        values.put("dSTSavings", getDSTSavings());
        values.put("department", getDepartment());
        values.put("division", getDivision());
        values.put("email", getEmail());
        values.put("expressivePhotoMod", getExpressivePhotoMod());
        values.put("fullName", getFullName());
        values.put("introduction", getIntroduction());
        values.put("isAboutMeTextEnabled", getIsAboutMeTextEnabled());
        values.put("isAllowUploadBGPhoto", getIsAllowUploadBGPhoto());
        values.put("isPercentCompleteEnabled", getIsPercentCompleteEnabled());
        values.put("isShowAsOfDate", getIsShowAsOfDate());
        values.put("isShowEditLink", getIsShowEditLink());
        values.put("isTimeZoneInDaylightTime", getIsTimeZoneInDaylightTime());
        values.put("liveProfileOriginalPhotoId", getLiveProfileOriginalPhotoId());
        values.put("liveProfilePhotoId", getLiveProfilePhotoId());
        values.put("liveProfilePhotoMod", getLiveProfilePhotoMod());
        values.put("localTimeEnabled", getLocalTimeEnabled());
        values.put("location", getLocation());
        values.put("mediaServiceBaseUrl", getMediaServiceBaseUrl());
        values.put("myNameAudioDeleteUrl", getMyNameAudioDeleteUrl());
        values.put("myNameAudioGetFileUrl", getMyNameAudioGetFileUrl());
        values.put("myNameAudioStatusUrl", getMyNameAudioStatusUrl());
        values.put("myNameAudioUploadUrl", getMyNameAudioUploadUrl());
        values.put("myNameEnabled", getMyNameEnabled());
        values.put("myNameText", getMyNameText());
        values.put("myNameToken", getMyNameToken());
        values.put("myNameUploadId", getMyNameUploadId());
        values.put("phoneNumbers", getPhoneNumbers());
        values.put("showLiveProfilePhoto", getShowLiveProfilePhoto());
        values.put("socialAccounts", getSocialAccounts());
        values.put("socialNetworks", getSocialNetworks());
        values.put("targetUserId", getTargetUserId());
        values.put("timezone", getTimezone());
        values.put("title", getTitle());
        values.put("userName", getUserName());
        values.put("utcOffset", getUtcOffset());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("aboutMeVideoDeleteUrl")) {
                final Object value = values.remove("aboutMeVideoDeleteUrl");
                if ((value == null)||(!value.equals(getAboutMeVideoDeleteUrl()))) {
                    setAboutMeVideoDeleteUrl(((String) value));
                }
            }
            if (values.containsKey("aboutMeVideoEnabled")) {
                final Object value = values.remove("aboutMeVideoEnabled");
                if ((value == null)||(!value.equals(getAboutMeVideoEnabled()))) {
                    setAboutMeVideoEnabled(((Boolean) value));
                }
            }
            if (values.containsKey("aboutMeVideoGetFileUrl")) {
                final Object value = values.remove("aboutMeVideoGetFileUrl");
                if ((value == null)||(!value.equals(getAboutMeVideoGetFileUrl()))) {
                    setAboutMeVideoGetFileUrl(((String) value));
                }
            }
            if (values.containsKey("aboutMeVideoStatusUrl")) {
                final Object value = values.remove("aboutMeVideoStatusUrl");
                if ((value == null)||(!value.equals(getAboutMeVideoStatusUrl()))) {
                    setAboutMeVideoStatusUrl(((String) value));
                }
            }
            if (values.containsKey("aboutMeVideoToken")) {
                final Object value = values.remove("aboutMeVideoToken");
                if ((value == null)||(!value.equals(getAboutMeVideoToken()))) {
                    setAboutMeVideoToken(((String) value));
                }
            }
            if (values.containsKey("aboutMeVideoUploadId")) {
                final Object value = values.remove("aboutMeVideoUploadId");
                if ((value == null)||(!value.equals(getAboutMeVideoUploadId()))) {
                    setAboutMeVideoUploadId(((String) value));
                }
            }
            if (values.containsKey("aboutMeVideoUploadUrl")) {
                final Object value = values.remove("aboutMeVideoUploadUrl");
                if ((value == null)||(!value.equals(getAboutMeVideoUploadUrl()))) {
                    setAboutMeVideoUploadUrl(((String) value));
                }
            }
            if (values.containsKey("applicationId")) {
                final Object value = values.remove("applicationId");
                if ((value == null)||(!value.equals(getApplicationId()))) {
                    setApplicationId(((String) value));
                }
            }
            if (values.containsKey("businessPhone")) {
                final Object value = values.remove("businessPhone");
                if ((value == null)||(!value.equals(getBusinessPhone()))) {
                    setBusinessPhone(((String) value));
                }
            }
            if (values.containsKey("cellPhone")) {
                final Object value = values.remove("cellPhone");
                if ((value == null)||(!value.equals(getCellPhone()))) {
                    setCellPhone(((String) value));
                }
            }
            if (values.containsKey("dSTSavings")) {
                final Object value = values.remove("dSTSavings");
                if ((value == null)||(!value.equals(getDSTSavings()))) {
                    setDSTSavings(((Integer) value));
                }
            }
            if (values.containsKey("department")) {
                final Object value = values.remove("department");
                if ((value == null)||(!value.equals(getDepartment()))) {
                    setDepartment(((String) value));
                }
            }
            if (values.containsKey("division")) {
                final Object value = values.remove("division");
                if ((value == null)||(!value.equals(getDivision()))) {
                    setDivision(((String) value));
                }
            }
            if (values.containsKey("email")) {
                final Object value = values.remove("email");
                if ((value == null)||(!value.equals(getEmail()))) {
                    setEmail(((String) value));
                }
            }
            if (values.containsKey("expressivePhotoMod")) {
                final Object value = values.remove("expressivePhotoMod");
                if ((value == null)||(!value.equals(getExpressivePhotoMod()))) {
                    setExpressivePhotoMod(((String) value));
                }
            }
            if (values.containsKey("fullName")) {
                final Object value = values.remove("fullName");
                if ((value == null)||(!value.equals(getFullName()))) {
                    setFullName(((String) value));
                }
            }
            if (values.containsKey("introduction")) {
                final Object value = values.remove("introduction");
                if ((value == null)||(!value.equals(getIntroduction()))) {
                    setIntroduction(((String) value));
                }
            }
            if (values.containsKey("isAboutMeTextEnabled")) {
                final Object value = values.remove("isAboutMeTextEnabled");
                if ((value == null)||(!value.equals(getIsAboutMeTextEnabled()))) {
                    setIsAboutMeTextEnabled(((Boolean) value));
                }
            }
            if (values.containsKey("isAllowUploadBGPhoto")) {
                final Object value = values.remove("isAllowUploadBGPhoto");
                if ((value == null)||(!value.equals(getIsAllowUploadBGPhoto()))) {
                    setIsAllowUploadBGPhoto(((Boolean) value));
                }
            }
            if (values.containsKey("isPercentCompleteEnabled")) {
                final Object value = values.remove("isPercentCompleteEnabled");
                if ((value == null)||(!value.equals(getIsPercentCompleteEnabled()))) {
                    setIsPercentCompleteEnabled(((Boolean) value));
                }
            }
            if (values.containsKey("isShowAsOfDate")) {
                final Object value = values.remove("isShowAsOfDate");
                if ((value == null)||(!value.equals(getIsShowAsOfDate()))) {
                    setIsShowAsOfDate(((Boolean) value));
                }
            }
            if (values.containsKey("isShowEditLink")) {
                final Object value = values.remove("isShowEditLink");
                if ((value == null)||(!value.equals(getIsShowEditLink()))) {
                    setIsShowEditLink(((Boolean) value));
                }
            }
            if (values.containsKey("isTimeZoneInDaylightTime")) {
                final Object value = values.remove("isTimeZoneInDaylightTime");
                if ((value == null)||(!value.equals(getIsTimeZoneInDaylightTime()))) {
                    setIsTimeZoneInDaylightTime(((Boolean) value));
                }
            }
            if (values.containsKey("liveProfileOriginalPhotoId")) {
                final Object value = values.remove("liveProfileOriginalPhotoId");
                if ((value == null)||(!value.equals(getLiveProfileOriginalPhotoId()))) {
                    setLiveProfileOriginalPhotoId(((Long) value));
                }
            }
            if (values.containsKey("liveProfilePhotoId")) {
                final Object value = values.remove("liveProfilePhotoId");
                if ((value == null)||(!value.equals(getLiveProfilePhotoId()))) {
                    setLiveProfilePhotoId(((Long) value));
                }
            }
            if (values.containsKey("liveProfilePhotoMod")) {
                final Object value = values.remove("liveProfilePhotoMod");
                if ((value == null)||(!value.equals(getLiveProfilePhotoMod()))) {
                    setLiveProfilePhotoMod(((String) value));
                }
            }
            if (values.containsKey("localTimeEnabled")) {
                final Object value = values.remove("localTimeEnabled");
                if ((value == null)||(!value.equals(getLocalTimeEnabled()))) {
                    setLocalTimeEnabled(((Boolean) value));
                }
            }
            if (values.containsKey("location")) {
                final Object value = values.remove("location");
                if ((value == null)||(!value.equals(getLocation()))) {
                    setLocation(((String) value));
                }
            }
            if (values.containsKey("mediaServiceBaseUrl")) {
                final Object value = values.remove("mediaServiceBaseUrl");
                if ((value == null)||(!value.equals(getMediaServiceBaseUrl()))) {
                    setMediaServiceBaseUrl(((String) value));
                }
            }
            if (values.containsKey("myNameAudioDeleteUrl")) {
                final Object value = values.remove("myNameAudioDeleteUrl");
                if ((value == null)||(!value.equals(getMyNameAudioDeleteUrl()))) {
                    setMyNameAudioDeleteUrl(((String) value));
                }
            }
            if (values.containsKey("myNameAudioGetFileUrl")) {
                final Object value = values.remove("myNameAudioGetFileUrl");
                if ((value == null)||(!value.equals(getMyNameAudioGetFileUrl()))) {
                    setMyNameAudioGetFileUrl(((String) value));
                }
            }
            if (values.containsKey("myNameAudioStatusUrl")) {
                final Object value = values.remove("myNameAudioStatusUrl");
                if ((value == null)||(!value.equals(getMyNameAudioStatusUrl()))) {
                    setMyNameAudioStatusUrl(((String) value));
                }
            }
            if (values.containsKey("myNameAudioUploadUrl")) {
                final Object value = values.remove("myNameAudioUploadUrl");
                if ((value == null)||(!value.equals(getMyNameAudioUploadUrl()))) {
                    setMyNameAudioUploadUrl(((String) value));
                }
            }
            if (values.containsKey("myNameEnabled")) {
                final Object value = values.remove("myNameEnabled");
                if ((value == null)||(!value.equals(getMyNameEnabled()))) {
                    setMyNameEnabled(((Boolean) value));
                }
            }
            if (values.containsKey("myNameText")) {
                final Object value = values.remove("myNameText");
                if ((value == null)||(!value.equals(getMyNameText()))) {
                    setMyNameText(((String) value));
                }
            }
            if (values.containsKey("myNameToken")) {
                final Object value = values.remove("myNameToken");
                if ((value == null)||(!value.equals(getMyNameToken()))) {
                    setMyNameToken(((String) value));
                }
            }
            if (values.containsKey("myNameUploadId")) {
                final Object value = values.remove("myNameUploadId");
                if ((value == null)||(!value.equals(getMyNameUploadId()))) {
                    setMyNameUploadId(((String) value));
                }
            }
            if (values.containsKey("showLiveProfilePhoto")) {
                final Object value = values.remove("showLiveProfilePhoto");
                if ((value == null)||(!value.equals(getShowLiveProfilePhoto()))) {
                    setShowLiveProfilePhoto(((Boolean) value));
                }
            }
            if (values.containsKey("targetUserId")) {
                final Object value = values.remove("targetUserId");
                if ((value == null)||(!value.equals(getTargetUserId()))) {
                    setTargetUserId(((String) value));
                }
            }
            if (values.containsKey("timezone")) {
                final Object value = values.remove("timezone");
                if ((value == null)||(!value.equals(getTimezone()))) {
                    setTimezone(((String) value));
                }
            }
            if (values.containsKey("title")) {
                final Object value = values.remove("title");
                if ((value == null)||(!value.equals(getTitle()))) {
                    setTitle(((String) value));
                }
            }
            if (values.containsKey("userName")) {
                final Object value = values.remove("userName");
                if ((value == null)||(!value.equals(getUserName()))) {
                    setUserName(((String) value));
                }
            }
            if (values.containsKey("utcOffset")) {
                final Object value = values.remove("utcOffset");
                if ((value == null)||(!value.equals(getUtcOffset()))) {
                    setUtcOffset(((Integer) value));
                }
            }
        }
        // structured properties
        {
            if (values.containsKey("customFields")) {
                final Object value = values.remove("customFields");
                if (value instanceof Map) {
                    if (getCustomFields_2() == null) {
                        setCustomFields_2(new COUserInfoElementBean());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getCustomFields_2().fromMap(inputMap);
                }
                if ((value == null)&&(getCustomFields_2()!= null)) {
                    setCustomFields_2(null);
                }
            }
            if (values.containsKey("phoneNumbers")) {
                final Object value = values.remove("phoneNumbers");
                if (value instanceof Map) {
                    if (getPhoneNumbers() == null) {
                        setPhoneNumbers(new COUserInfoElementBean());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getPhoneNumbers().fromMap(inputMap);
                }
                if ((value == null)&&(getPhoneNumbers()!= null)) {
                    setPhoneNumbers(null);
                }
            }
            if (values.containsKey("socialAccounts")) {
                final Object value = values.remove("socialAccounts");
                if (value instanceof Map) {
                    if (getSocialAccounts() == null) {
                        setSocialAccounts(new COSocialAccountBean());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getSocialAccounts().fromMap(inputMap);
                }
                if ((value == null)&&(getSocialAccounts()!= null)) {
                    setSocialAccounts(null);
                }
            }
            if (values.containsKey("socialNetworks")) {
                final Object value = values.remove("socialNetworks");
                if (value instanceof Map) {
                    if (getSocialNetworks() == null) {
                        setSocialNetworks(new COUserInfoElementBean());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getSocialNetworks().fromMap(inputMap);
                }
                if ((value == null)&&(getSocialNetworks()!= null)) {
                    setSocialNetworks(null);
                }
            }
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
