
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;
import com.sdk.test.vdm.namespaces.sfodataedmx.selectable.PicklistOptionSelectable;


/**
 * Fluent helper to fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class PicklistOptionByKeyFluentHelper
    extends FluentHelperByKey<PicklistOptionByKeyFluentHelper, PicklistOption, PicklistOptionSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} entity with the provided key field values. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to fetch a single {@code PicklistOption}
     * @param id
     *     
     */
    public PicklistOptionByKeyFluentHelper(
        @Nonnull
        final String servicePath, final Long id) {
        super(servicePath);
        this.key.put("id", id);
    }

    @Override
    @Nonnull
    protected Class<PicklistOption> getEntityClass() {
        return PicklistOption.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
