
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * RuleFieldMappingBeanList<p></p><p>Original complex type name from the Odata EDM: <b>RuleFieldMappingBeanList</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class RuleFieldMappingBeanList
    extends VdmComplex<RuleFieldMappingBeanList>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>ruleFieldMappings</b></p>
     * 
     * @param ruleFieldMappings
     *     
     */
    @SerializedName("ruleFieldMappings")
    @JsonProperty("ruleFieldMappings")
    @Nullable
    @ODataField(odataName = "ruleFieldMappings")
    private RuleFieldMappingBean ruleFieldMappings;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<RuleFieldMappingBeanList> getType() {
        return RuleFieldMappingBeanList.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("ruleFieldMappings", getRuleFieldMappings());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
        }
        // structured properties
        {
            if (values.containsKey("ruleFieldMappings")) {
                final Object value = values.remove("ruleFieldMappings");
                if (value instanceof Map) {
                    if (getRuleFieldMappings() == null) {
                        setRuleFieldMappings(new RuleFieldMappingBean());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getRuleFieldMappings().fromMap(inputMap);
                }
                if ((value == null)&&(getRuleFieldMappings()!= null)) {
                    setRuleFieldMappings(null);
                }
            }
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
