
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>SEFExtEventMetaDataList</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class SEFExtEventMetaDataList
    extends VdmComplex<SEFExtEventMetaDataList>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>data</b></p>
     * 
     * @param data
     *     
     */
    @SerializedName("data")
    @JsonProperty("data")
    @Nullable
    @ODataField(odataName = "data")
    private SEFExtEventMetaData data;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>status</b></p>
     * 
     * @param status
     *     
     */
    @SerializedName("status")
    @JsonProperty("status")
    @Nullable
    @ODataField(odataName = "status")
    private String status;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>statusMsg</b></p>
     * 
     * @param statusMsg
     *     
     */
    @SerializedName("statusMsg")
    @JsonProperty("statusMsg")
    @Nullable
    @ODataField(odataName = "statusMsg")
    private String statusMsg;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<SEFExtEventMetaDataList> getType() {
        return SEFExtEventMetaDataList.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("data", getData());
        values.put("status", getStatus());
        values.put("statusMsg", getStatusMsg());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("status")) {
                final Object value = values.remove("status");
                if ((value == null)||(!value.equals(getStatus()))) {
                    setStatus(((String) value));
                }
            }
            if (values.containsKey("statusMsg")) {
                final Object value = values.remove("statusMsg");
                if ((value == null)||(!value.equals(getStatusMsg()))) {
                    setStatusMsg(((String) value));
                }
            }
        }
        // structured properties
        {
            if (values.containsKey("data")) {
                final Object value = values.remove("data");
                if (value instanceof Map) {
                    if (getData() == null) {
                        setData(new SEFExtEventMetaData());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getData().fromMap(inputMap);
                }
                if ((value == null)&&(getData()!= null)) {
                    setData(null);
                }
            }
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
