
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.collect.Maps;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmComplex;
import com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataField;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;


/**
 * <p>Original complex type name from the Odata EDM: <b>SEFExtEventMetaData</b></p>
 * 
 */
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString(doNotUseGetters = true, callSuper = true)
@EqualsAndHashCode(doNotUseGetters = true, callSuper = true)
@JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataVdmEntityAdapterFactory.class)
public class SEFExtEventMetaData
    extends VdmComplex<SEFExtEventMetaData>
{

    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>description</b></p>
     * 
     * @param description
     *     
     */
    @SerializedName("description")
    @JsonProperty("description")
    @Nullable
    @ODataField(odataName = "description")
    private String description;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>effectiveDated</b></p>
     * 
     * @param effectiveDated
     *     
     */
    @SerializedName("effectiveDated")
    @JsonProperty("effectiveDated")
    @Nullable
    @JsonAdapter(com.sap.cloud.sdk.s4hana.datamodel.odata.adapter.ODataBooleanAdapter.class)
    @ODataField(odataName = "effectiveDated")
    private Boolean effectiveDated;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>entity</b></p>
     * 
     * @param entity
     *     
     */
    @SerializedName("entity")
    @JsonProperty("entity")
    @Nullable
    @ODataField(odataName = "entity")
    private String entity;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>entityKeys</b></p>
     * 
     * @param entityKeys
     *     
     */
    @SerializedName("entityKeys")
    @JsonProperty("entityKeys")
    @Nullable
    @ODataField(odataName = "entityKeys")
    private SEFEventEntityKey entityKeys;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>name</b></p>
     * 
     * @param name
     *     
     */
    @SerializedName("name")
    @JsonProperty("name")
    @Nullable
    @ODataField(odataName = "name")
    private String name;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>params</b></p>
     * 
     * @param params
     *     
     */
    @SerializedName("params")
    @JsonProperty("params")
    @Nullable
    @ODataField(odataName = "params")
    private SEFEventEntityParam params;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>publisher</b></p>
     * 
     * @param publisher
     *     
     */
    @SerializedName("publisher")
    @JsonProperty("publisher")
    @Nullable
    @ODataField(odataName = "publisher")
    private String publisher;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>topic</b></p>
     * 
     * @param topic
     *     
     */
    @SerializedName("topic")
    @JsonProperty("topic")
    @Nullable
    @ODataField(odataName = "topic")
    private String topic;
    /**
     * Constraints: Nullable<p>Original property from the Odata EDM: <b>type</b></p>
     * 
     * @param type_2
     *     
     */
    @SerializedName("type")
    @JsonProperty("type")
    @Nullable
    @ODataField(odataName = "type")
    private String type_2;

    /**
     * {@inheritDoc}
     * 
     */
    @Nonnull
    @Override
    public Class<SEFExtEventMetaData> getType() {
        return SEFExtEventMetaData.class;
    }

    @Nonnull
    @Override
    protected Map<String, Object> toMapOfFields() {
        final Map<String, Object> values = super.toMapOfFields();
        values.put("description", getDescription());
        values.put("effectiveDated", getEffectiveDated());
        values.put("entity", getEntity());
        values.put("entityKeys", getEntityKeys());
        values.put("name", getName());
        values.put("params", getParams());
        values.put("publisher", getPublisher());
        values.put("topic", getTopic());
        values.put("type", getType_2());
        return values;
    }

    @Override
    protected void fromMap(final Map<String, Object> inputValues) {
        final Map<String, Object> values = Maps.newHashMap(inputValues);
        // simple properties
        {
            if (values.containsKey("description")) {
                final Object value = values.remove("description");
                if ((value == null)||(!value.equals(getDescription()))) {
                    setDescription(((String) value));
                }
            }
            if (values.containsKey("effectiveDated")) {
                final Object value = values.remove("effectiveDated");
                if ((value == null)||(!value.equals(getEffectiveDated()))) {
                    setEffectiveDated(((Boolean) value));
                }
            }
            if (values.containsKey("entity")) {
                final Object value = values.remove("entity");
                if ((value == null)||(!value.equals(getEntity()))) {
                    setEntity(((String) value));
                }
            }
            if (values.containsKey("name")) {
                final Object value = values.remove("name");
                if ((value == null)||(!value.equals(getName()))) {
                    setName(((String) value));
                }
            }
            if (values.containsKey("publisher")) {
                final Object value = values.remove("publisher");
                if ((value == null)||(!value.equals(getPublisher()))) {
                    setPublisher(((String) value));
                }
            }
            if (values.containsKey("topic")) {
                final Object value = values.remove("topic");
                if ((value == null)||(!value.equals(getTopic()))) {
                    setTopic(((String) value));
                }
            }
            if (values.containsKey("type")) {
                final Object value = values.remove("type");
                if ((value == null)||(!value.equals(getType_2()))) {
                    setType_2(((String) value));
                }
            }
        }
        // structured properties
        {
            if (values.containsKey("entityKeys")) {
                final Object value = values.remove("entityKeys");
                if (value instanceof Map) {
                    if (getEntityKeys() == null) {
                        setEntityKeys(new SEFEventEntityKey());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getEntityKeys().fromMap(inputMap);
                }
                if ((value == null)&&(getEntityKeys()!= null)) {
                    setEntityKeys(null);
                }
            }
            if (values.containsKey("params")) {
                final Object value = values.remove("params");
                if (value instanceof Map) {
                    if (getParams() == null) {
                        setParams(new SEFEventEntityParam());
                    }
                    @SuppressWarnings("unchecked")
                    final Map<String, Object> inputMap = ((Map<String, Object> ) value);
                    getParams().fromMap(inputMap);
                }
                if ((value == null)&&(getParams()!= null)) {
                    setParams(null);
                }
            }
        }
        // navigation properties
        {
        }
        super.fromMap(values);
    }

    @Nonnull
    @Override
    protected Map<String, Object> getKey() {
        final Map<String, Object> result = Maps.newHashMap();
        return result;
    }

}
