
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.net.URI;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.google.common.collect.Maps;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestinationProperties;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperFunction;
import com.sap.cloud.sdk.datamodel.odata.helper.ODataTypeValueSerializer;
import com.sap.cloud.sdk.odatav2.connectivity.ODataException;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.olingo.odata2.api.edm.EdmSimpleTypeKind;


/**
 * Fluent helper for the <b>sendEmailToInterviewers</b> OData function import.
 * 
 */
public class SendEmailToInterviewersFluentHelper
    extends FluentHelperFunction<SendEmailToInterviewersFluentHelper, String, String>
{

    private final Map<String, Object> values = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will execute the <b>sendEmailToInterviewers</b> OData function import with the provided parameters. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param interviewers
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>interviewers</b></p>
     * @param servicePath
     *     Service path to be used to call the functions against.
     * @param attachResume
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>attachResume</b></p>
     * @param hiringManagerNote
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>hiringManagerNote</b></p>
     * @param attachCoverLetter
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>attachCoverLetter</b></p>
     * @param applicationId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>applicationId</b></p>
     * @param attachInterviewGuide
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>attachInterviewGuide</b></p>
     */
    public SendEmailToInterviewersFluentHelper(
        @Nonnull
        final String servicePath, final Long applicationId, final String interviewers, final Boolean attachResume, final Boolean attachCoverLetter, final Boolean attachInterviewGuide, final String hiringManagerNote) {
        super(servicePath);
        values.put("applicationId", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Int64).toUri(applicationId));
        values.put("interviewers", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(interviewers));
        values.put("attachResume", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Boolean).toUri(attachResume));
        values.put("attachCoverLetter", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Boolean).toUri(attachCoverLetter));
        values.put("attachInterviewGuide", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Boolean).toUri(attachInterviewGuide));
        values.put("hiringManagerNote", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(hiringManagerNote));
    }

    @Override
    @Nonnull
    protected Class<String> getEntityClass() {
        return String.class;
    }

    @Override
    @Nonnull
    protected String getFunctionName() {
        return "sendEmailToInterviewers";
    }

    @Override
    @Nullable
    protected JsonElement refineJsonResponse(
        @Nullable
        JsonElement jsonElement) {
        if ((jsonElement instanceof JsonObject)&&((JsonObject) jsonElement).has(getFunctionName())) {
            jsonElement = ((JsonObject) jsonElement).get(getFunctionName());
        }
        return super.refineJsonResponse(jsonElement);
    }

    @Override
    @Nonnull
    protected Map<String, Object> getParameters() {
        return values;
    }

    @Override
    @Nonnull
    protected HttpUriRequest createRequest(
        @Nonnull
        final URI uri) {
        return new HttpPost(uri);
    }

    @Override
    @Nullable
    public String execute(
        @Nonnull
        final HttpDestinationProperties destination)
        throws ODataException
    {
        return super.executeSingle(destination);
    }

}
