
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.net.URI;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.google.common.collect.Maps;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestinationProperties;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperFunction;
import com.sap.cloud.sdk.datamodel.odata.helper.ODataTypeValueSerializer;
import com.sap.cloud.sdk.odatav2.connectivity.ODataException;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.olingo.odata2.api.edm.EdmSimpleTypeKind;


/**
 * Fluent helper for the <b>sendMailOfferLetter</b> OData function import.
 * 
 */
public class SendMailOfferLetterFluentHelper
    extends FluentHelperFunction<SendMailOfferLetterFluentHelper, String, String>
{

    private final Map<String, Object> values = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will execute the <b>sendMailOfferLetter</b> OData function import with the provided parameters. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param offerLetterId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>offerLetterId</b></p>
     * @param servicePath
     *     Service path to be used to call the functions against.
     * @param bodyLocale
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>bodyLocale</b></p>
     * @param bodyTemplateId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>bodyTemplateId</b></p>
     * @param sendMode
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>sendMode</b></p>
     */
    public SendMailOfferLetterFluentHelper(
        @Nonnull
        final String servicePath, final Long offerLetterId, final String sendMode, final Long bodyTemplateId, final String bodyLocale) {
        super(servicePath);
        values.put("offerLetterId", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Int64).toUri(offerLetterId));
        values.put("sendMode", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(sendMode));
        values.put("bodyTemplateId", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Int64).toUri(bodyTemplateId));
        values.put("bodyLocale", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(bodyLocale));
    }

    @Override
    @Nonnull
    protected Class<String> getEntityClass() {
        return String.class;
    }

    @Override
    @Nonnull
    protected String getFunctionName() {
        return "sendMailOfferLetter";
    }

    @Override
    @Nullable
    protected JsonElement refineJsonResponse(
        @Nullable
        JsonElement jsonElement) {
        if ((jsonElement instanceof JsonObject)&&((JsonObject) jsonElement).has(getFunctionName())) {
            jsonElement = ((JsonObject) jsonElement).get(getFunctionName());
        }
        return super.refineJsonResponse(jsonElement);
    }

    @Override
    @Nonnull
    protected Map<String, Object> getParameters() {
        return values;
    }

    @Override
    @Nonnull
    protected HttpUriRequest createRequest(
        @Nonnull
        final URI uri) {
        return new HttpGet(uri);
    }

    @Override
    @Nullable
    public String execute(
        @Nonnull
        final HttpDestinationProperties destination)
        throws ODataException
    {
        return super.executeSingle(destination);
    }

}
