
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.net.URI;
import java.util.Map;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import com.google.common.collect.Maps;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestinationProperties;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperFunction;
import com.sap.cloud.sdk.datamodel.odata.helper.ODataTypeValueSerializer;
import com.sap.cloud.sdk.odatav2.connectivity.ODataException;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.olingo.odata2.api.edm.EdmSimpleTypeKind;


/**
 * Fluent helper for the <b>setSmsNotificationPreference</b> OData function import.
 * 
 */
public class SetSmsNotificationPreferenceFluentHelper
    extends FluentHelperFunction<SetSmsNotificationPreferenceFluentHelper, String, String>
{

    private final Map<String, Object> values = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will execute the <b>setSmsNotificationPreference</b> OData function import with the provided parameters. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to call the functions against.
     * @param isoCountryCode
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>isoCountryCode</b></p>
     * @param optIn
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>optIn</b></p>
     * @param candidateId
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>candidateId</b></p>
     * @param cellPhone
     *     Constraints: none<p>Original parameter name from the Odata EDM: <b>cellPhone</b></p>
     */
    public SetSmsNotificationPreferenceFluentHelper(
        @Nonnull
        final String servicePath, final Boolean optIn, final Long candidateId, final String isoCountryCode, final String cellPhone) {
        super(servicePath);
        values.put("optIn", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Boolean).toUri(optIn));
        values.put("candidateId", ODataTypeValueSerializer.of(EdmSimpleTypeKind.Int64).toUri(candidateId));
        values.put("isoCountryCode", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(isoCountryCode));
        values.put("cellPhone", ODataTypeValueSerializer.of(EdmSimpleTypeKind.String).toUri(cellPhone));
    }

    @Override
    @Nonnull
    protected Class<String> getEntityClass() {
        return String.class;
    }

    @Override
    @Nonnull
    protected String getFunctionName() {
        return "setSmsNotificationPreference";
    }

    @Override
    @Nullable
    protected JsonElement refineJsonResponse(
        @Nullable
        JsonElement jsonElement) {
        if ((jsonElement instanceof JsonObject)&&((JsonObject) jsonElement).has(getFunctionName())) {
            jsonElement = ((JsonObject) jsonElement).get(getFunctionName());
        }
        return super.refineJsonResponse(jsonElement);
    }

    @Override
    @Nonnull
    protected Map<String, Object> getParameters() {
        return values;
    }

    @Override
    @Nonnull
    protected HttpUriRequest createRequest(
        @Nonnull
        final URI uri) {
        return new HttpPost(uri);
    }

    @Override
    @Nullable
    public String execute(
        @Nonnull
        final HttpDestinationProperties destination)
        throws ODataException
    {
        return super.executeSingle(destination);
    }

}
