
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperDelete;


/**
 * Fluent helper to delete an existing {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity in the S/4HANA system.<p>
 * To perform execution, call the {@link #execute execute} method on the fluent helper object.
 * 
 */
public class UserDeleteFluentHelper
    extends FluentHelperDelete<UserDeleteFluentHelper, User>
{

    /**
     * {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity object that will be deleted in the S/4HANA system.
     * 
     */
    private final User entity;

    /**
     * Creates a fluent helper object that will delete a {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity on the OData endpoint. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     The service path to direct the update requests to.
     * @param entity
     *     The User to delete from the endpoint.
     */
    public UserDeleteFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final User entity) {
        super(servicePath);
        this.entity = entity;
    }

    @Override
    @Nonnull
    protected User getEntity() {
        return entity;
    }

}
