
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperRead;
import com.sdk.test.vdm.namespaces.sfodataedmx.selectable.UserSelectable;


/**
 * Fluent helper to fetch multiple {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entities. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class UserFluentHelper
    extends FluentHelperRead<UserFluentHelper, User, UserSelectable>
{


    /**
     * Creates a fluent helper using the specified service path to send the read requests.
     * 
     * @param servicePath
     *     The service path to direct the read requests to.
     */
    public UserFluentHelper(
        @Nonnull
        final String servicePath) {
        super(servicePath);
    }

    @Override
    @Nonnull
    protected Class<User> getEntityClass() {
        return User.class;
    }

}
