
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx;

import java.util.Map;
import javax.annotation.Nonnull;
import com.google.common.collect.Maps;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperByKey;
import com.sdk.test.vdm.namespaces.sfodataedmx.selectable.UserSelectable;


/**
 * Fluent helper to fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity using key fields. This fluent helper allows methods which modify the underlying query to be called before executing the query itself. 
 * 
 */
public class UserByKeyFluentHelper
    extends FluentHelperByKey<UserByKeyFluentHelper, User, UserSelectable>
{

    private final Map<String, Object> key = Maps.newHashMap();

    /**
     * Creates a fluent helper object that will fetch a single {@link com.sdk.test.vdm.namespaces.sfodataedmx.User User} entity with the provided key field values. To perform execution, call the {@link #execute execute} method on the fluent helper object.
     * 
     * @param servicePath
     *     Service path to be used to fetch a single {@code User}
     * @param userId
     *     
     */
    public UserByKeyFluentHelper(
        @Nonnull
        final String servicePath, final String userId) {
        super(servicePath);
        this.key.put("userId", userId);
    }

    @Override
    @Nonnull
    protected Class<User> getEntityClass() {
        return User.class;
    }

    @Override
    @Nonnull
    protected Map<String, Object> getKey() {
        return key;
    }

}
