
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.link;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.EntityLink;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmObject;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel;
import com.sdk.test.vdm.namespaces.sfodataedmx.selectable.PicklistLabelSelectable;


/**
 * Template class to represent entity navigation links of {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistLabel PicklistLabel} to other entities. Instances of this object are used in query modifier methods of the entity
 * fluent helpers. Contains methods to compare a field's value with a provided value.
 * 
 * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData
 * field names, so use the constructor with caution.
 * 
 * @param <ObjectT>
 * Entity type of subclasses from {@link com.sap.cloud.sdk.datamodel.odata.helper.VdmObject VdmObject}.
 * 
 */
public class PicklistLabelLink<ObjectT extends VdmObject<?> >
    extends EntityLink<PicklistLabelLink<ObjectT> , PicklistLabel, ObjectT>
    implements PicklistLabelSelectable
{


    /**
     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.
     * 
     * @param fieldName
     *     OData navigation field name. Must match the field returned by the underlying OData service.
     */
    public PicklistLabelLink(final String fieldName) {
        super(fieldName);
    }

    private PicklistLabelLink(final EntityLink<PicklistLabelLink<ObjectT> , PicklistLabel, ObjectT> toClone) {
        super(toClone);
    }

    @Nonnull
    @Override
    protected PicklistLabelLink<ObjectT> translateLinkType(final EntityLink<PicklistLabelLink<ObjectT> , PicklistLabel, ObjectT> link) {
        return new PicklistLabelLink<ObjectT>(link);
    }

}
