
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 3.15.1
 */

package com.sdk.test.vdm.namespaces.sfodataedmx.link;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.EntityLink;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmObject;
import com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption;
import com.sdk.test.vdm.namespaces.sfodataedmx.selectable.PicklistOptionSelectable;


/**
 * Template class to represent entity navigation links of {@link com.sdk.test.vdm.namespaces.sfodataedmx.PicklistOption PicklistOption} to other entities. Instances of this object are used in query modifier methods of the entity
 * fluent helpers. Contains methods to compare a field's value with a provided value.
 * 
 * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData
 * field names, so use the constructor with caution.
 * 
 * @param <ObjectT>
 * Entity type of subclasses from {@link com.sap.cloud.sdk.datamodel.odata.helper.VdmObject VdmObject}.
 * 
 */
public class PicklistOptionLink<ObjectT extends VdmObject<?> >
    extends EntityLink<PicklistOptionLink<ObjectT> , PicklistOption, ObjectT>
    implements PicklistOptionSelectable
{


    /**
     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.
     * 
     * @param fieldName
     *     OData navigation field name. Must match the field returned by the underlying OData service.
     */
    public PicklistOptionLink(final String fieldName) {
        super(fieldName);
    }

    private PicklistOptionLink(final EntityLink<PicklistOptionLink<ObjectT> , PicklistOption, ObjectT> toClone) {
        super(toClone);
    }

    @Nonnull
    @Override
    protected PicklistOptionLink<ObjectT> translateLinkType(final EntityLink<PicklistOptionLink<ObjectT> , PicklistOption, ObjectT> link) {
        return new PicklistOptionLink<ObjectT>(link);
    }

}
